### ISSUE TITLE
Does not use my resume in the data folder

### ISSUE THREAD

**Issue by james00543** [feder-cr/Auto_Jobs_Applier_AIHawk#142]
Hi, I ran the command as instructed, but it does not start the application.

**Comment by felippesantia** [comment]
same here

**Comment by Andres-Ventura** [comment]
auto jobs apps never work well long term given consistent integration of new elements and renamings inside linkedin homepage html

**Comment by Andres-Ventura** [comment]
@james00543 what do you mean by not start?

**Comment by Vent3st** [comment]
I tried something similar, added --resume /path/ to the .pdf in the data folder and I am still prompted to choose between the default resume templates (modern, classic, css) versus running with the .pdf I provided.

**Comment by mahimachowdarym** [comment]
It worked for me when I used the full path instead of the relative one. 
However, I have an issue with Open AI tiers and couldn't use the application even when the code works fine.

**Comment by feder-cr** [comment]
@james00543 @mahimachowdarym @felippesantia  I really don't understand the problem: join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by air55555** [comment]
@james00543, did you solved the problem by updating path value?

**Comment by james00543** [comment]
> @james00543, did you solve the problem by updating path value?

No, even if I used the full path.

**Comment by feder-cr** [comment]
@james00543 any update?

**Comment by james00543** [comment]
still doesn't work.

**Comment by josylad** [comment]
> still doesn't work.

Join the TG group and also provide screenshots of error.

**Comment by craschnet** [comment]
Have you tried to use
`python3 main.py --reusme <Path to Resume.pdf>`
