### ISSUE TITLE
Feature Request: Implement LinkedIn Boolean Search Functionality

### ISSUE THREAD

**Issue by mustafaslk** [feder-cr/Auto_Jobs_Applier_AIHawk#183]
# Feature Request: LinkedIn Boolean Search Integration

## Description
Implement LinkedIn's Boolean search functionality within LinkedIn_AIHawk to allow for more precise and powerful job searches.

## Proposed Functionality
- Add support for quoted searches for exact phrases
- Implement NOT searches to exclude specific terms
- Add OR searches to broaden results
- Support AND searches for combining multiple terms
- Allow parenthetical searches for complex queries

## Implementation Details
1. Update the search function to parse Boolean operators (AND, OR, NOT)
2. Add support for quotation marks to denote exact phrases
3. Implement parentheses handling for complex queries
4. Modify the search algorithm to respect the order of precedence:
   1. Quotes [""]
   2. Parentheses [()]
   3. NOT
   4. AND
   5. OR

## Benefits
- More precise job searches
- Ability to exclude irrelevant results
- Increased flexibility in defining search criteria
- Better alignment with LinkedIn's native search capabilities

## Additional Notes
- The + and - operators are not supported by LinkedIn, so we should use AND and NOT instead
- Wildcard "*" searches are not supported by LinkedIn and should not be implemented

## Examples
- "product manager"
- programmer NOT manager
- sales OR marketing OR advertising
- accountant AND finance AND CPA
- VP NOT (assistant OR SVP)

This feature would significantly enhance the search capabilities of LinkedIn_AIHawk, allowing users to perform more targeted job searches.

**Comment by feder-cr** [comment]
@mustafaslk do you want work on this?
