### ISSUE TITLE
Feature Request: Add Region Code Search Functionality

### ISSUE THREAD

**Issue by mustafaslk** [feder-cr/Auto_Jobs_Applier_AIHawk#184]
## Description
Enhance location search capabilities to include support for region codes such as EMEA (Europe, Middle East, and Africa) and NAMER (North America). This feature will allow users to broaden their job search to entire regions rather than specific countries or cities.

## Proposed Functionality
- Add support for searching jobs by region codes (e.g., EMEA, NAMER, APAC, LATAM)
- Implement a mapping system to translate region codes into the corresponding countries and cities
- Allow users to combine region codes with specific locations for more flexible searches

## Implementation Details
1. Create a mapping of region codes to their constituent countries and major cities
2. Update the `config.yaml` file to include a new field for region codes
3. Modify the search function to recognize and process region codes
4. Implement logic to expand region codes into a list of relevant locations for the job search
5. Update the user interface (if applicable) to allow input of region codes

## Benefits
- Broadens job search capabilities to entire regions
- Simplifies the process of searching for jobs across multiple countries
- Aligns with common recruiting practices that often use region codes
- Increases the chances of finding relevant opportunities in desired geographical areas

## Additional Notes
- Consider implementing the most common region codes first: EMEA, NAMER, APAC, LATAM
- Future iterations could include more specific sub-regions (e.g., DACH for Germany, Austria, Switzerland)
- Ensure that the feature respects LinkedIn's search limitations and terms of service

## Example Usage
```yaml
# In config.yaml
locations:
  - EMEA
  - "New York"
  - APAC
```

This configuration would search for jobs in all of Europe, the Middle East, and Africa, as well as specifically in New York, and in the Asia-Pacific region.

## Potential Challenges
- Ensuring accurate and up-to-date mapping of region codes to countries
- Handling potential conflicts between region codes and specific locations
- Managing the increased complexity of search queries

This feature would significantly enhance the geographical search capabilities of LinkedIn_AIHawk, allowing users to cast a wider net in their job search while still maintaining specificity when needed.

**Comment by feder-cr** [comment]
@mustafaslk do you want work on this?
