### ISSUE TITLE
Boolean issues in config.yaml

### ISSUE THREAD

**Issue by pablosecuen** [feder-cr/Auto_Jobs_Applier_AIHawk#298]
i keep getting that typo errors, for example , sintax is completly fine, i performed installation twice, keep getting same error

![image](https://github.com/user-attachments/assets/2d111416-ce97-4152-bfc3-79577c19f406)

![image](https://github.com/user-attachments/assets/fe8a5c39-6ffb-4d76-8f0c-ff5e9042dff7)

**Comment by prvshah51** [comment]
Can you validate the yaml file once ? Just paste your yaml file here  : https://www.yamllint.com/

**Comment by azjz92** [comment]
This did not help me for the newest version, I'm looking into it, i just copied the example config file but it didn't work for me this time and it said my yaml was good

**Comment by birmehto** [comment]
same for me as well

**Comment by triii10** [comment]
This seems to be happening because the dictionary that config.yaml is converted to expects the key 'mid_senior level' with spaces. YAML keys don't support spaces, but python dictionaries do. 
It should be simple to just add an underscore in the expected dictionary key.

I can take up this issue and create a PR.

**Comment by triii10** [comment]
Upon further thought, @pablosecuen if you try the example YAML and make sure you get the underscores and the dashes in the YAML keys correctly - 
`mid-senior level: true`

I understand the YAML keys get converted to dict keys which further create the URL for filtering the jobs, but for keeping the YAML keys consistent, it will be better to not add the space in this specific key. @feder-cr thoughts on this?

**Comment by feder-cr** [comment]
@triii10 assigned

**Comment by rishabredhu** [comment]
try this - 
![image](https://github.com/user-attachments/assets/dd35c80d-df18-4808-be66-97b35ea84e4a)

**Comment by Anurag2809** [comment]
looks like you modified the mid_senior level to mid_senior_level you should be good to go

**Comment by chaitanyapanja** [comment]
Configuration error: Invalid type for key 'remote' in config file data_folder\config.yaml. Expected <class 'bool'>.
Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

I am still getting above error

**Comment by testacc12345678900** [comment]
> Configuration error: Invalid type for key 'remote' in config file data_folder\config.yaml. Expected <class 'bool'>. Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration
> 
> I am still getting above error

hey did you solve this issue? @chaitanyapanja

**Comment by NobelShaji** [comment]
Configuration error: Invalid type for key 'remote' in config file data_folder\config.yaml. Expected <class 'bool'>.
Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

Still getting this error even after validating the yaml. Can anyone help?

**Comment by feder-cr** [comment]
@triii10 any update?
