### ISSUE TITLE
Configuration error with internship key in config.yaml

### ISSUE THREAD

**Issue by GregFree** [feder-cr/Auto_Jobs_Applier_AIHawk#306]
Summary:
Encountering persistent **_Configuration error: Experience level 'internship' must be a boolean_** while setting up the LinkedIn_AIHawk tool. This issue persists even though the **_internship_** key is correctly placed in the **_jobTypes_** section. Various troubleshooting steps were taken to resolve it, but the error remains, suggesting potential script misinterpretation of the **_internship_** key.

Details:
Environment:
OS: Windows 11
Python Version: 3.12.5
LinkedIn_AIHawk Repository Version: Latest from [GitHub repository](https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application)

Problem:
I keep receiving the following error:

**_Configuration error: Experience level 'internship' must be a boolean in config file data_folder\config.yaml_**
Despite correctly placing the **_internship_** key in the **_jobTypes_** section of **_config.yaml,_** the script seems to incorrectly interpret it as part of the **_experienceLevel_** section.

Steps Taken:
Validation of **_config.yaml_**:
Verified that the **_internship_** key is only present under the **_jobTypes_** section and is set as a boolean (**_true_** or **_false_**).
Removed the **_internship_** key entirely to isolate the issue, but the error persists.
Ran the YAML file through [YAML Lint](http://www.yamllint.com/) to validate its structure, and it passes.

Test with Simplified Configurations:
Simplified the **_config.yaml_** to minimal sections to isolate the problem (including only **_remote,_** **_experienceLevel_**, **_jobTypes_**, etc.), but the error remains focused on **_internship_**.

Independent YAML Test:
Created a small Python script to independently test the loading of **_config.yaml_**. The file loads correctly without errors, indicating the problem may lie within the script itself rather than the YAML configuration.
Output from the YAML test confirmed correct parsing:
**_{'remote': False, 'experienceLevel': {'entryLevel': False, 'midLevel': False, 'seniorLevel': True, 'management': True}, 'jobTypes': {'full_time': True, 'part_time': False, 'contract': True, 'volunteer': False}, 'date': {'last_24_hours': True, 'last_7_days': False, 'last_14_days': False}, 'positions': [...], 'locations': [...], 'distance': 25}_**

File Encoding and Re-cloning:
Verified file encoding as UTF-8.
Deleted and re-cloned the repository, reapplying the configuration file but the error persists.

Script Review:
Reviewed the **_main.py_** script and YAML handling logic but didn’t identify any clear misconfigurations.
No references to **_internship_** in **_experienceLevel_**, yet the error suggests it’s being processed incorrectly.

Screenshots:
See attached.
![Screenshot 2024-09-06 160753](https://github.com/user-attachments/assets/38e8a403-64c9-4bb3-bb30-035eb8f89bc0)

Conclusion:
It seems the script might be misinterpreting the internship key. Any guidance or clarification on how the script processes the config.yaml file, particularly the internship key, would be greatly appreciated.

**Comment by feder-cr** [comment]
@GregFree do you want work on this?

**Comment by feder-cr** [comment]
@GregFree any uodate?

**Comment by feder-cr** [comment]
fixed on last version
