### ISSUE TITLE
Session not created error

### ISSUE THREAD

**Issue by Hivra1** [feder-cr/Auto_Jobs_Applier_AIHawk#336]
When I try to execute the command python main.py, I receive the error "Session not created/runtime error," but it does load the blank Chrome browser. Could someone please help me with the issue? 

![image](https://github.com/user-attachments/assets/6cdcb915-3983-4162-9c54-bca61e184602)

![image](https://github.com/user-attachments/assets/9b3814d2-903b-4603-853c-d1332c38fc2a)

**Comment by feder-cr** [comment]
@Hivra1 any update?

**Comment by Hivra1** [comment]
Thank you for asking. But I still have the same issue. I tried restarting the computer and launching the python main file several times but still had the same problem. I also tried to check/install on a separate computer, but the issue still existed.

**Comment by feder-cr** [comment]
@Hivra1 try v3

**Comment by Hivra1** [comment]
@feder-cr I tried the v3 version, but I'm still having the same problem. I'm installing on Windows 11. Is it something a windows issue, since I observed in the readme file that it was indicated to install in Windows 10 and Ubuntu 22?

**Comment by feder-cr** [comment]
@Hivra1 any update? join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
