### ISSUE TITLE
Provide a Docker installation

### ISSUE THREAD

**Issue by timoa** [feder-cr/Auto_Jobs_Applier_AIHawk#343]
I will start working on the dockerization of the project. I will send the PR when ready.

Let me know if there is already a task in progress. Thanks!

**Comment by PatilHrushikesh** [comment]
Hi timoa, I can help you dockering this, please share your status

**Comment by timoa** [comment]
Thanks, @PatilHrushikesh!
I created the Dockerfile and a basic bash script to use as an entry point since there are two different scripts (main.py & resume_yaml_generator.py on the v3 branch).
I will try to test the build today and make sure that all the commands are running without issue.
I will share my branch for review as soon as I have something working 👍

**Comment by timoa** [comment]
There is an issue right now with the Python dependencies and I can't build.
I will retry with the #353 PR and see if it is working

**Comment by feder-cr** [comment]
too many problems with chromedriver

**Comment by gustavosett** [comment]
hey @timoa and @PatilHrushikesh, I've just started this containerization in a fork, any contribution is welcome.

[Containered_Auto_Jobs_Applier_AIHawk](https://github.com/gustavosett/Containered_Auto_Jobs_Applier_AIHawk)
