### ISSUE TITLE
Add user checkpoints

### ISSUE THREAD

**Issue by youngchingjui** [feder-cr/Auto_Jobs_Applier_AIHawk#358]
This is more of a design request. But it would be good to allow the user a little more control over a few things in this automated process:
- Approving / denying which jobs to apply for
- Approving / editing the customized CVs

This might require some thinking around how to re-design the flow of this application.

**Comment by feder-cr** [comment]
@youngchingjui do you want work on this?

**Comment by youngchingjui** [comment]
Yes, I can. I'll submit a pull request in a few days

**Comment by feder-cr** [comment]
@youngchingjui ok, work on V3 and join on telegram group

**Comment by feder-cr** [comment]
@youngchingjui any update?

**Comment by feder-cr** [comment]
@youngchingjui  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by youngchingjui** [comment]
Hi @feder-cr sorry for not responding promptly. I'm currently engaged with something else and cannot support this ticket currently.
