### ISSUE TITLE
[FEATURE]: Have a dynamic plain_text_resume.yaml

### ISSUE THREAD

**Issue by virajtshah** [feder-cr/Auto_Jobs_Applier_AIHawk#369]
### Feature summary

one should be able to modify the requirements of plain_text_resume.yaml as per their needs

**Comment by virajtshah** [comment]
I did that but still it isnt running. Its giving error for YAML Schema. My resume doesn't consist of project, exam and skills in experience section. i have it separate from experience. I modified it even generated schema using python its almost similar still the script didnt run. Also i wanted to use my resume for auto apply but it gave YAML error even when parsing PDF  file

**Comment by feder-cr** [comment]
@virajtshah  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
