### ISSUE TITLE
[INVALID]: <Provide a brief title> Error running the bot: Education.__init__()

### ISSUE THREAD

**Issue by lohith80** [feder-cr/Auto_Jobs_Applier_AIHawk#370]
### Reason for invalidation

I have followed the steps in the readme.txt

### Steps to validate

C:\Windows\System32\LinkedIn_AIHawk_automatic_job_application>python main.py
Runtime error: Error running the bot: Education.__init__() got an unexpected keyword argument 'education_level'
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

**Comment by josylad** [comment]
Hello, 
Check your yaml file and compare it with the sample provided.

**Comment by feder-cr** [comment]
@lohith80  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
