### ISSUE TITLE
[BUG]: getting modules error

### ISSUE THREAD

**Issue by zoheb799** [feder-cr/Auto_Jobs_Applier_AIHawk#371]
### Describe the bug

LinkedIn_AIHawk_automatic_job_application/main.py", line 16, in <module>     from src.linkedIn_job_manager import LinkedInJobManager LinkedIn_AIHawk_automatic_job_application/src/linkedIn_job_manager.py", line 8, in <module>     from inputimeout import inputimeout, TimeoutOccurred # type: ignore ModuleNotFoundError: No module named 'inputimeout'

### Steps to reproduce

take the latest pull
just cli the command 
python3 main.py

### Environment

None

**Comment by ralyodio** [comment]
check your yaml files for merge conflicts.

**Comment by zoheb799** [comment]
- How ban i get the openai api link?? llm_api_url:
      - Link of the API endpoint for the LLM model
         - openai: https://api.pawan.krd/cosmosrp/v1
         - ollama: http://127.0.0.1:11434/
         - claude: https://api.anthropic.com/v1
         - gemini: no api_url
      - Note: To run local Ollama, follow the guidelines here: Guide to
   Ollama deployment <https://github.com/ollama/ollama>

**Comment by ralyodio** [comment]
huh?

**Comment by zoheb799** [comment]
Sorry how can I get that...llm api url
Openai as there's mentioned like...https://api.pawan.krd/cosmosrp/v1

**Comment by ralyodio** [comment]
This is in my `config.yaml`:

```
llm_model_type: openai
llm_model: gpt-4o 
llm_api_url: https://api.pawan.krd/cosmosrp/v1
```

The `secrets.yaml` has this:

```
llm_api_key: sk-l7xxxxx
```

**Comment by zoheb799** [comment]
That is what...how can I create my own api link..?..
Just tell me the process

**Comment by ralyodio** [comment]
just use that one.

**Comment by zoheb799** [comment]
still im getting the same error

please help
Traceback (most recent call last):
  File "/home/desktop/LinkedIn_AIHawk_automatic_job_application/main.py",
line 16, in <module>
    from src.linkedIn_job_manager import LinkedInJobManager
  File
"/home/Desktop/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_job_manager.py",
line 8, in <module>
    from inputimeout import inputimeout, TimeoutOccurred
ModuleNotFoundError: No module named 'inputimeout'

**Comment by ralyodio** [comment]
yeah that's missing dependency just do `pip install inputimeout`

**Comment by zoheb799** [comment]
im getting this error
Runtime error: Error running the bot: Education.__init__() got an
unexpected keyword argument 'education_level'
Refer to the configuration and troubleshooting guide:
https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

education_details:
- education_level: "Bachelor's Degree"

**Comment by ralyodio** [comment]
I think that's old. Do this:

```
education_details:
  - degree: "Bachelor of Science Business Administration"
    university: "San Diego State University"
    gpa: "3.0"
    graduation_year: "1998"
    field_of_study: "Business Administration"
```

**Comment by zoheb799** [comment]
But my  degree is a bachelor of engineering

**Comment by ralyodio** [comment]
so change it obviously. that's just from my resume.

**Comment by zoheb799** [comment]
I'm getting these many errors..
help me to get rid of this
Traceback (most recent call last):
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py",
line 60, in job_apply
    self.gpt_answerer.set_job(job)
  File "/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/gpt.py",
line 147, in set_job

self.job.set_summarize_job_description(self.summarize_job_description(self.job.description))
  File "/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/gpt.py",
line 158, in summarize_job_description
    output = chain.invoke({"text": text})
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/base.py",
line 2875, in invoke
    input = step.invoke(input, config)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/base.py",
line 4441, in invoke
    return self._call_with_config(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/base.py",
line 1784, in _call_with_config
    context.run(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/config.py",
line 404, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/base.py",
line 4297, in _invoke
    output = call_func_with_variable_args(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/config.py",
line 404, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/gpt.py",
line 86, in __call__
    reply = self.llm(messages)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/_api/deprecation.py",
line 168, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py",
line 976, in __call__
    generation = self.generate(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py",
line 571, in generate
    raise e
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py",
line 561, in generate
    self._generate_with_cache(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py",
line 793, in _generate_with_cache
    result = self._generate(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_openai/chat_models/base.py",
line 589, in _generate
    response = self.client.create(**payload)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_utils/_utils.py",
line 277, in wrapper
    return func(*args, **kwargs)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/resources/chat/completions.py",
line 646, in create
    return self._post(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream,
stream_cls=stream_cls))
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 942, in request
    return self._request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1031, in _request
    return self._retry_request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1079, in _retry_request
    return self._request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1031, in _request
    return self._retry_request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1079, in _retry_request
    return self._request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You
exceeded your current quota, please check your plan and billing details.
For more information on this error, read the docs:
https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type':
'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_job_manager.py",
line 126, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py",
line 65, in job_apply
    raise Exception(f"Failed to apply to job! Original exception:
\nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception:
Traceback:
Traceback (most recent call last):
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py",
line 60, in job_apply
    self.gpt_answerer.set_job(job)
  File "/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/gpt.py",
line 147, in set_job

self.job.set_summarize_job_description(self.summarize_job_description(self.job.description))
  File "/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/gpt.py",
line 158, in summarize_job_description
    output = chain.invoke({"text": text})
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/base.py",
line 2875, in invoke
    input = step.invoke(input, config)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/base.py",
line 4441, in invoke
    return self._call_with_config(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/base.py",
line 1784, in _call_with_config
    context.run(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/config.py",
line 404, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/base.py",
line 4297, in _invoke
    output = call_func_with_variable_args(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/runnables/config.py",
line 404, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/src/gpt.py",
line 86, in __call__
    reply = self.llm(messages)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/_api/deprecation.py",
line 168, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py",
line 976, in __call__
    generation = self.generate(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py",
line 571, in generate
    raise e
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py",
line 561, in generate
    self._generate_with_cache(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py",
line 793, in _generate_with_cache
    result = self._generate(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/langchain_openai/chat_models/base.py",
line 589, in _generate
    response = self.client.create(**payload)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_utils/_utils.py",
line 277, in wrapper
    return func(*args, **kwargs)
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/resources/chat/completions.py",
line 646, in create
    return self._post(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream,
stream_cls=stream_cls))
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 942, in request
    return self._request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1031, in _request
    return self._retry_request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1079, in _retry_request
    return self._request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1031, in _request
    return self._retry_request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1079, in _retry_request
    return self._request(
  File
"/home/zoheb/Desktop/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.10/site-packages/openai/_base_client.py",
line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You
exceeded your current quota, please check your plan and billing details.
For more information on this error, read the docs:
https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type':
'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

**Comment by air55555** [comment]
@zoheb799 pls update fresh bot ver and confirm if you STILL have this weird error

**Comment by feder-cr** [comment]
@zoheb799 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
