### ISSUE TITLE
Other language option - Question before start

### ISSUE THREAD

**Issue by supaeasy** [feder-cr/Auto_Jobs_Applier_AIHawk#393]
Hi there

before I am getting into setting this up I have a question: Readme says:
_LinkedIn language To ensure the bot works, your LinkedIn language must be set to English._

Does that mean this only works for generating applications in english or is this just about the language setting in LinkedIn? Is it possible to generate everything in other languages? German, in my case.

Thanks a lot.

**Comment by felipedick** [comment]
Hi! I've set LinkedIn to English, but my resume is in Portuguese, andif you use an specific PDF resume for all applications, it works fine. However, the customized ChatGPT resume contains parts in English. If you'd like to use the customized ChatGPT resume in a different language, you'll need to adjust the headers in the CV template file located at "lib_resume_builder_AIHawk/template_base.py."

**Comment by feder-cr** [comment]
@felipedick @supaeasy join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
