### ISSUE TITLE
Funny bug when a DM window is open in LinkedIn

### ISSUE THREAD

**Issue by anonymousalligator213** [feder-cr/Auto_Jobs_Applier_AIHawk#397]
Hi, 
I had the bot set up and running on my Raspberry Pi 4 (after a bit of a struggle), and it was accessing my Linkedin Premium account without incident for a couple of days. Then I noticed this really funny bug that seems to happen when LinkedIn is also open elsewhere (say, on my phone). The bot seemed to be getting confused with some of the prompts at the time a new DM window opened from a hiring manager (HM).  The result was this hilarious exchange, with last one being actually from me when I woke up and checked Linkedin the next day: 

![FunnyBug](https://github.com/user-attachments/assets/4f14e047-77f0-4748-b2ad-c0fbe5dacaea)

The bot was taking overnight liberties with my communications, every few minutes! I am fairly certain that this is the bot's work, because I saw new messages appear later in the same open window _while I was sitting there watching it and not doing anything_! And as further confirmation, the messages in that DM window stopped as soon as I killed the bot on my Raspberry Pi. 

While this didn't do much damage to my applications, please do look into this very unexpected problem! Hiring managers are the last people that anyone would want to clown around with, even though this one was pretty relaxed about it!

**Comment by feder-cr** [comment]
@anonymousalligator213 share log please hahaha
