### ISSUE TITLE
Configuration Error: Missing or Invalid Key

### ISSUE THREAD

**Issue by deshneni-akhil** [feder-cr/Auto_Jobs_Applier_AIHawk#399]
#361 the issue is exactly as 361. I have gone through the readme file and run the main file where I have updated my data in data_folder currently encountered the following error. 

linkedIn_auto_jobs_applier_with_AI git:(main) py main.py                     
Configuration error: Missing or invalid key 'experienceLevel' in config file data_folder/config.yaml
Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

Any insights on how I can resolve this error ? 

Config. yaml file in question

remote: true

experience_level:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: false
  internship: true
  other: false
  volunteer: false

date:
  all time: false
  month: true
  week: true
  24 hours: true

positions:
  - Software Developer
  - Software Engineer
  - Backend Engineer
  - DevOps Engineer
  - Backend Developer
  - Web Developer
  - Full Stack Developer
  - Software Tester

locations:
  - USA
  - India

apply_once_at_company: true

distance: 1000

company_blacklist:
  - Amazon

title_blacklist:
  - Data Science
  - Senior
  - Director
  - Executive

job_applicants_threshold:
  min_applicants: 20
  max_applicants: 500

**Comment by Syerramsetti915** [comment]
there is a typo error change "experience_level" to "experienceLevel"

**Comment by feder-cr** [comment]
@deshneni-akhil @Syerramsetti915 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
