### ISSUE TITLE
configuration error:  Invalid type for key

### ISSUE THREAD

**Issue by testacc12345678900** [feder-cr/Auto_Jobs_Applier_AIHawk#403]
Hey, im having this error despite to having a boolean value in config.yaml

**Configuration error: Invalid type for key 'remote' in config file data_folder\config.yaml. Expected <class 'bool'>.
Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration**

Any help would be appreciated.

**Comment by thomHayner** [comment]
Hi @testacc12345678900, there appears to be a misconfiguration, it was updated and is now looking for both a string and a bool...

[src/job_application_profile.py](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/74d7dd6e107e361ad18244d5b5daaeb7cb1ca9cd/src/job_application_profile.py#L26)
```
line 26:    remote_work: str
```

[main.py](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/74d7dd6e107e361ad18244d5b5daaeb7cb1ca9cd/main.py#L44)
```
line 44:            'remote': bool,
```

Try these steps:
1. remove 'remote' entirely from ```config.yaml```
2. use a string ```["Yes"/"No"]``` for 'remote_work' in ```plain_text_resume.yaml```
3. update line 44 in ```main.py``` to be either ```'remote': dict,```, ```'remote': string,```, or ```'remote': str,``` (sorry I can't be more specific, I'm not a python dev)
4. report back on what did and did not work

Thanks!

**Comment by testacc12345678900** [comment]
thank u that worked totally!
and now i have another error that says;

**Runtime error: Error running the bot: Unexpected error while parsing YAML: 3 validation errors for Resume
education_details.0.final_evaluation_grade
  Field required [type=missing, input_value={'education_level': "Bach...': 'Computer Science'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.0.start_date
  Field required [type=missing, input_value={'education_level': "Bach...': 'Computer Science'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.0.year_of_completion
  Field required [type=missing, input_value={'education_level': "Bach...': 'Computer Science'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration**

im trying to remove the grade and exam in the education section

**Comment by feder-cr** [comment]
@testacc12345678900 share your resume and join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
