### ISSUE TITLE
Bug: chromedriver.exe Hardcoded in site-packages/lib_resume_builder_AIHawk/utils.py Causes Compatibility Issues on macOS

### ISSUE THREAD

**Issue by udaylunawat** [feder-cr/Auto_Jobs_Applier_AIHawk#405]
### Bug: `chromedriver.exe` Hardcoded in `lib_resume_builder_AIHawk/utils.py` Causes Compatibility Issues on macOS

**Description:**

The current implementation of the `create_driver_selenium()` function in `lib_resume_builder_AIHawk/utils.py` contains the following line:

```python
chromedriver_path = os.path.join(folder, "chromedriver.exe")
```

This hardcodes the ChromeDriver path to the `.exe` extension, which causes compatibility issues on macOS, as `.exe` files are specific to Windows.

**Steps to Reproduce:**

1. Clone the repository on a macOS system.
2. Run the application.
3. Observe that the application fails to initialize ChromeDriver due to the `.exe` path being used.

**Expected Behavior:**

The application should work across different operating systems, including macOS, without requiring manual intervention to change the file extension.

**Actual Behavior:**

The application crashes on macOS because it cannot find or execute `chromedriver.exe`.

**Proposed Fix:**

The line:

```python
chromedriver_path = os.path.join(folder, "chromedriver.exe")
```

was replaced with:

```python
chromedriver_path = ChromeDriverManager().install()
```

This allows `webdriver-manager` to dynamically fetch the appropriate ChromeDriver for the user's operating system, ensuring compatibility across platforms.

**Suggested Change:**

Replace the hardcoded path with `ChromeDriverManager().install()` to make the application OS-agnostic.

**Additional Context:**

This change was made and tested on macOS, resolving the issue.
```

**Comment by KenjaminButton** [comment]
You are a true genius and a saint. It's working perfectly for me now. Thank you.

**Comment by feder-cr** [comment]
@udaylunawat hi, bro do you want work on PR? join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by feder-cr** [comment]
@udaylunawat sny update?

**Comment by feder-cr** [comment]
@KenjaminButton @udaylunawat @MuilaerteJunior  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
