### ISSUE TITLE
Issue with cover letter upload

### ISSUE THREAD

**Issue by ParthSoni-CS** [feder-cr/Auto_Jobs_Applier_AIHawk#412]
Hi the gpt is providing cover letter but it's is not properly lined, here is what I mean 
[tmpfftsuua6.pdf](https://github.com/user-attachments/files/17080224/tmpfftsuua6.pdf)
<img width="630" alt="image" src="https://github.com/user-attachments/assets/960c2d84-050e-40f0-bc7f-09231d808315">

**Comment by feder-cr** [comment]
@ParthSoni-CS use the last version

**Comment by RohanBera** [comment]
I had the same issue! I unfortunately did not notice it for like 150 applications cuz the cover letters are temporary and are not stored on our system. I updated my code to store the cover letters along with the generated CVs, and that's when I noticed! 

anyways, here is a quick fix I used:
in your src/linkedin_easy_applier.py, in function _create_and_upload_cover_letter(), 

import these: 
```
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph
```

replace 

```
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_pdf_file:
            letter_path = temp_pdf_file.name
            c = canvas.Canvas(letter_path, pagesize=letter)
            _, height = letter
            text_object = c.beginText(100, height - 100)
            text_object.setFont("Helvetica", 12)
            text_object.textLines(cover_letter)
            c.drawText(text_object)
            c.save()
            element.send_keys(letter_path)
```

with 

```
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_pdf_file:
            letter_path = temp_pdf_file.name 
            doc = SimpleDocTemplate(letter_path, pagesize=letter)

            styles = getSampleStyleSheet()
            style = styles["Normal"]  

            paragraph = Paragraph(cover_letter, style)
            doc.build([paragraph])

            element.send_keys(letter_path)
```

Hope this helps!

**Comment by feder-cr** [comment]
fixed @RohanBera @ParthSoni-CS join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
