### ISSUE TITLE
Configuration error: Invalid type for key 'remote' in config file data_folder/config.yaml. Expected <class 'bool'>.

### ISSUE THREAD

**Issue by ar-shayeb** [feder-cr/Auto_Jobs_Applier_AIHawk#414]
Hey All
The version I am using of python is Python 3.11.9
PS: I AM NOT A PROGRAMMER, SO PLEASE KEEP IT SIMPLE :D

I am using Mac, I did everything then when I tried to enter python main.py

The terminal wrote this:

python main.py
Configuration error: Invalid type for key 'remote' in config file data_folder/config.yaml. Expected <class 'bool'>.
Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration
(virtual) ar.shayeb@Abdulrahmans-MacBook-Air LinkedIn_AIHawk_automatic_job_application %

**Comment by NobelShaji** [comment]
> Hey All The version I am using of python is Python 3.11.9 PS: I AM NOT A PROGRAMMER, SO PLEASE KEEP IT SIMPLE :D
> 
> I am using Mac, I did everything then when I tried to enter python main.py
> 
> The terminal wrote this:
> 
> python main.py Configuration error: Invalid type for key 'remote' in config file data_folder/config.yaml. Expected <class 'bool'>. Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration (virtual) ar.shayeb@Abdulrahmans-MacBook-Air LinkedIn_AIHawk_automatic_job_application %

i am facing the same issue. Please do help once its fixed

**Comment by maathimself** [comment]
Remove the square brackets.

**Comment by NobelShaji** [comment]
> Remove the square brackets.

which square brackets in which file?

**Comment by Shaon2221** [comment]
`python main.py
Runtime error: Error running the bot: Education.__init__() got an unexpected keyword argument 'education_level'
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration`

**Comment by maathimself** [comment]
> > Remove the square brackets.
> 
> which square brackets in which file?

The file that is referenced in the error you posted.
