### ISSUE TITLE
Observations

### ISSUE THREAD

**Issue by 999AICoder** [feder-cr/Auto_Jobs_Applier_AIHawk#424]
This utility has been incredibly helpful in my job search. Below are a few observations and suggestions after extended use:

### Suggestions:
- **Updating the Repo Locally**: Pulling updates is tricky since modified files are part of the repo. Suggestion: include `<file_name>_example.yaml` and prompt users to create proper files before running. This also prevents using defaults by accident.
  
- **Inconsistent Naming**: YAML parameters use both camel case and underscores. Consistency would improve configuration and maintenance.

- **Company Blacklist**: Not working on the main or v3 branches. I created a local workaround using `data_folder/output/success.json` to manually update the blacklist between runs. Suggestion: make this a built-in feature with configuration options.

- **"How did you hear about us"**: When this is a text field sometimes has odd values. Suggestion: default to "LinkedIn" or provide a config option for default.

- **Bot-Like Answers**: Some answers suggest bot-generated responses, e.g., "I don't have information for First Last..." (where "First Last" is the applicant). Suggestion: add sanity checks for response length, especially for short expected answers. Optionally log questionable responses or introduce a "strict" mode.

- **Job History**: It would be helpful to have a detailed log of all job applications and responses for reference, especially when contacted for an interview. This would also help with debugging.
 

### Bug:
- **Cover Letter Bug**: Textbox cover letters are reused, sometimes including the wrong company name. Suggestion: prevent reuse of form fields, especially for cover letters.

- **stringWidth Bug** In `linkedin_easy_applier.py`, `utils.stringWidth` is referenced but doesn't exist. I fixed it locally by importing `stringWidth` from `reportlab.pdfbase.pdfmetrics`.

- **Hiring Manager Questions**: Inadequate handling of these, though I lack specific examples at the moment to share.

**Comment by feder-cr** [comment]
hi @999AICoder , I would be so happy to accept your PR!
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
