### ISSUE TITLE
[BUG]: using quotes doesn't work

### ISSUE THREAD

**Issue by ralyodio** [feder-cr/Auto_Jobs_Applier_AIHawk#431]
### Describe the bug

need to allow for quoted keywords

### Steps to reproduce

```
positions:
  - "Frontend Engineer"
  - "Fullstack Engineer" JavaScript
  - Director Engineering
  - VP Engineering
  - "Fractional CTO"
  - "Technical Co-founder"
   ```

### Branch

None

**Comment by feder-cr** [comment]
@ralyodio please explain better

**Comment by newbie321** [comment]
The easiest way to solve it right now would be to go here:
```
 def next_job_page(self, position, location, job_page):
        logger.debug(f"Navigating to next job page: {position} in {location}, page {job_page}")
        self.driver.get(
            f"https://www.linkedin.com/jobs/search/{self.base_search_url}&keywords={position}{location}&start={job_page * 25}")

```
and 
1) replace outer quotes with with single quotes 
2) add "" around {position}  ie `"{position}"`

**Comment by feder-cr** [comment]
@newbie321 please make a PR

**Comment by newbie321** [comment]
> @newbie321 please make a PR

There is no PR that needs to be made to address this issue.   YAML natively supports quoted text.   you just have to escape it with single quotes... 
in other words, this is not a bug; but rather users lack of knowledge of YAML.   
They need to enter text in YAML compatible format:  
for example ' "medical doctor" ' instead of medical doctor

**Comment by feder-cr** [comment]
@newbie321 ok thanks

**Comment by ralyodio** [comment]
say what?

**Comment by ralyodio** [comment]
so it should be like this??

```
positions:
  - '"Frontend Engineer"'
  - '"Fullstack Engineer"' JavaScript
  - '"Director Engineering"'
  - '"VP Engineering"'
  - '"Fractional CTO"'
  - '"Technical Co-founder"'
  ```

**Comment by ralyodio** [comment]
```
$ python main.py
2024-10-06 15:16:58.736 | ERROR    | __main__:main:205 - Configuration error: Error reading file data_folder/config.yaml: while parsing a block collection
  in "data_folder/config.yaml", line 27, column 3
expected <block end>, but found '<scalar>'
  in "data_folder/config.yaml", line 28, column 28
2024-10-06 15:16:58.736 | ERROR    | __main__:main:206 - Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/AIHawk_AIHawk_automatic_job_application/blob/main/readme.md#configuration Error reading file data_folder/config.yaml: while parsing a block collection
  in "data_folder/config.yaml", line 27, column 3
expected <block end>, but found '<scalar>'
  in "data_folder/config.yaml", line 28, column 28
```

**Comment by newbie321** [comment]
> ```
> $ python main.py
> 2024-10-06 15:16:58.736 | ERROR    | __main__:main:205 - Configuration error: Error reading file data_folder/config.yaml: while parsing a block collection
>   in "data_folder/config.yaml", line 27, column 3
> expected <block end>, but found '<scalar>'
>   in "data_folder/config.yaml", line 28, column 28
> 2024-10-06 15:16:58.736 | ERROR    | __main__:main:206 - Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/AIHawk_AIHawk_automatic_job_application/blob/main/readme.md#configuration Error reading file data_folder/config.yaml: while parsing a block collection
>   in "data_folder/config.yaml", line 27, column 3
> expected <block end>, but found '<scalar>'
>   in "data_folder/config.yaml", line 28, column 28
> ```

Why do not you start with something simple, like a single position instead of a bunch,
Try '"Frontend Engineer"' and see what happens.... 
attached are the screenshots showing YAML parses quoted text natively.  

![mail_clerk_1](https://github.com/user-attachments/assets/7d35af10-fe63-4a30-8233-e6c1dde3022b)
![mail_clerk_2](https://github.com/user-attachments/assets/258604a1-3ac7-4557-9bd5-2c9a04c71eb7)
