### ISSUE TITLE
[DOCS]:  error installing required packages

### ISSUE THREAD

**Issue by Ariugth** [feder-cr/Auto_Jobs_Applier_AIHawk#439]
### Affected documentation section

requirements.txt

### Documentation improvement description

when I am trying to install the required packages I get an error saying "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'". When I saw the installation tutorial on YouTube, the content of the requirements.txt document is different from the one I downloaded to clone the folder on my computer, I don't know if that is perhaps the reason for the error I get.
P.S. I'm new to installing github files.

### Why is this change necessary?

to proceed with the installation

**Comment by ChristOscar** [comment]
Can you upload or copy what is in your required packages.txt?

**Comment by Ariugth** [comment]
This is the requirements.txt file that is downloaded to me

[requirements.txt](https://github.com/user-attachments/files/17177188/requirements.txt)

**Comment by RushiChaganti** [comment]
Message in the telegram group
 https://t.me/AIhawkCommunity/59
I will help you out there

**Comment by Ariugth** [comment]
> Message in the telegram group https://t.me/AIhawkCommunity/59 I will help you out there

thanks, I already wrote in the group

**Comment by RushiChaganti** [comment]
@Ariugth Has something been done about your problem? If so, kindly close this case.

**Comment by feder-cr** [comment]
@ChristOscar @RushiChaganti @Ariugth  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
