### ISSUE TITLE
[QUESTION]: Want help to generate resume based on JD

### ISSUE THREAD

**Issue by Raviteja9-git** [feder-cr/Auto_Jobs_Applier_AIHawk#440]
### Summary of your question

Bot is not generating resume based on job description

### Question details

The application is running fine for me but when its submitting the resume for every job its submitting the same resume. Its not tailoring resume according to the job description. Please anyone help me in this issue. Thanks in advance.

**Comment by feder-cr** [comment]
@Raviteja9-git join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by sachinlodhi** [comment]
I also have the same issue. The bot is using the default resume that is available on LinkedIn.
