### ISSUE TITLE
[QUESTION]: Does it works only for "Easy Apply" in LinkedIn? Does this automation work for "Apply" which navigates to external systems such as Workday?

### ISSUE THREAD

**Issue by sreenivasmrpivot** [feder-cr/Auto_Jobs_Applier_AIHawk#446]
### Summary of your question

Does it works only for "Easy Apply" in LinkedIn? Does this automation work for Apply which navigates to external systems such as Workday?

### Question details

LinkedIn has 2 ways of applying to jobs.
1. Easy Apply (Varying Pop-up HTML view(s).)
2. Apply (This navigates to external websites of employer which is usually workday based.)

Based on my initial read, I think this tool works only for "Easy Apply" and does not support "Apply".

Please confirm my understanding.

**Comment by craschnet** [comment]
From what I've seen in the code, it only using the "Easy Apply" button.

**Comment by alvinchun** [comment]
Does anyone know whether there is such AI bot apply for external systems such as Workday etc.?

**Comment by suhel-nz** [comment]
I imagine that would be challenging to implement because every firm would have a different set of fields in its workday application form. 

You could navigate to the external site and ask an LLM to infer the form field. However, it's likely complex and challenging to get consistently accurate results.

**Comment by ralyodio** [comment]
> Does anyone know whether there is such AI bot apply for external systems such as Workday etc.?

Yes, there is one: https://github.com/sentient-engineering/jobber
