### ISSUE TITLE
[FEATURE]: Create a local data store (postgress or something else) which can keep a track of applications and prevent duplication and track progress along interview process

### ISSUE THREAD

**Issue by sreenivasmrpivot** [feder-cr/Auto_Jobs_Applier_AIHawk#447]
### Feature summary

Create a local data store (postgress or something else) which can keep a track of applications and prevent duplication and track progress along interview process

### Feature description

Applying for jobs is just the initial step. However there are other exhausting parts of the process.

1. Avoiding duplication in application
2. Keeping track of the applied jobs
3. Maintaining progress of interview journey across multiple interviews
4. Reminders for interview slots etc.

I think, having this tracking in place is key to letting the candidate focus on interview prep and getting maximum value.

### Motivation

Tracking and planning multiple interview loops simultaneously is a huge challenge.

**Comment by craschnet** [comment]
This is tracked in your LinkedIn profile:
https://www.linkedin.com/my-items/saved-jobs/

Since it uses LinkedIn's "Easy Apply," it should not apply twice.
