### ISSUE TITLE
[HELP WANTED]: <Provide a descriptive title> want to see the generated resume

### ISSUE THREAD

**Issue by vishwakarma-vishal** [feder-cr/Auto_Jobs_Applier_AIHawk#450]
### Issue description

The tools is really good, can you please tell me where can I see the generated resume?

**Comment by vishwakarma-vishal** [comment]
I haven't seen the resume can you help me brother 
<img width="202" alt="image" src="https://github.com/user-attachments/assets/1e9d970a-9169-4070-a36b-7a7f912c3c3b">

**Comment by AbhilashBharadwaj** [comment]
I don't have enough context.

You should see your generated cv, assuming :
1. The bot has run with no flags. `python main.py`
2. A job was encountered which satisfies your config requirements and the bot had to create a resume.

Let the bot run and monitor the logs.

**Comment by feder-cr** [comment]
@AbhilashBharadwaj @vishwakarma-vishal join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
