### ISSUE TITLE
[BUG]: Looping error when bot tries to apply to job

### ISSUE THREAD

**Issue by Random490** [feder-cr/Auto_Jobs_Applier_AIHawk#455]
### Describe the bug

When the bot finds a job it extracts and then says its starting the application and then it gives an error saying:  Error during job application: 'NoneType' object has no attribute 'strip' and then loops again doing the same thing

### Steps to reproduce

Happens every time I run the program and it finds a job, I have tried reinstalling and have also tried a different version of the program
![WindowsTerminal_nFeXDSnLA5](https://github.com/user-attachments/assets/0ca72041-a79d-4901-9519-f5f24a5b6397)
Attached a screenshot for reference. 

### Branch

main

### Python version

3.12.1

### LLM Used

Gemini

### Model used

gemini-pro

**Comment by Random490** [comment]
I wanted to also add that I am in Canada, not sure if there is a difference between LinkedIn's site here compared to the US

**Comment by nebnella** [comment]
Same here.

[outputlog3.log](https://github.com/user-attachments/files/17287704/outputlog3.log)

Python version 3.11.6 and it was painstaking to get it to run initially

**Comment by EdwardZehuaZhang** [comment]
Facing the same issue, and unfortunately running the example resume did not work either.

**Comment by feder-cr** [comment]
@Random490 @nebnella @EdwardZehuaZhang join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
