### ISSUE TITLE
[FEATURE]: Can we add additional fields to the legal_authorization section?

### ISSUE THREAD

**Issue by vedantwalia** [feder-cr/Auto_Jobs_Applier_AIHawk#459]
### Feature summary

The current template is designed for US/UK/EU/Canada only, is it possible to update this for additional locales?

### Feature description

legal_authorization:
  eu_work_authorization: "[Yes/No]"
  us_work_authorization: "[Yes/No]"
  requires_us_visa: "[Yes/No]"
  requires_us_sponsorship: "[Yes/No]"
  requires_eu_visa: "[Yes/No]"
  legally_allowed_to_work_in_eu: "[Yes/No]"
  legally_allowed_to_work_in_us: "[Yes/No]"
  requires_eu_sponsorship: "[Yes/No]"
  canada_work_authorization: "[Yes/No]"
  requires_canada_visa: "[Yes/No]"
  legally_allowed_to_work_in_canada: "[Yes/No]"
  requires_canada_sponsorship: "[Yes/No]"
  uk_work_authorization: "[Yes/No]"
  requires_uk_visa: "[Yes/No]"
  legally_allowed_to_work_in_uk: "[Yes/No]"
  requires_uk_sponsorship: "[Yes/No]"

I am not sure if it would work but if I replace the locale name with my country name, ideally it should work just find just that I am unsure how the backend code is based and incase this small tweak might break something 

any updates or insight on this would really be appreciated 

### Motivation

This would help this program to be usable globally

**Comment by RushiChaganti** [comment]
Hey @vedantwalia  We can include more fields in the legal authorization section, but doing so will break the code. I'm willing to assist with it, but we can't release a new version for each country, which is why we designed it this way.
You can contact me on telegram community 
https://t.me/AIhawkCommunity
