### ISSUE TITLE
[BUG]: Script Starting Chrome But Not Doing Anything

### ISSUE THREAD

**Issue by Desouki27** [feder-cr/Auto_Jobs_Applier_AIHawk#480]
### Describe the bug

i have the script setup with everything that is needed but when i try to run it, it starts chrome but then nothing happens after that, only around 20 seconds later chrome is closed and it shows the following error: "Message: session not created: DevToolsActivePort file doesn't exist"

### Expected behavior

going to linkedin.com

### Actual behavior

nothing

### Branch

None

### Python version

Python 3.11.9

### LLM Used

ChatGPT

### Model used

GPT-4o-mini

### Additional context

2024-10-06 18:51:51.178 | ERROR    | __main__:main:213 - Runtime error: Error running the bot: Failed to initialize browser: Message: session not created: DevToolsActivePort file doesn't exist
Stacktrace:
        GetHandleVerifier [0x00917143+25587]
        (No symbol) [0x008AA2E4]
        (No symbol) [0x007A2113]
        (No symbol) [0x007D7743]
        (No symbol) [0x007D39CE]
        (No symbol) [0x007CE689]
        (No symbol) [0x00814BE5]
        (No symbol) [0x0081436A]
        (No symbol) [0x0080A936]
        (No symbol) [0x007DBA73]
        (No symbol) [0x007DC4CD]
        GetHandleVerifier [0x00BF4C63+3030803]
        GetHandleVerifier [0x00C46B99+3366473]
        GetHandleVerifier [0x009A95F2+624802]
        GetHandleVerifier [0x009B0E6C+655644]
        (No symbol) [0x008B2C9D]
        (No symbol) [0x008AFD68]
        (No symbol) [0x008AFF05]
        (No symbol) [0x008A2336]
        BaseThreadInitThunk [0x75467BA9+25]
        RtlInitializeExceptionChain [0x772BC0CB+107]
        RtlClearBits [0x772BC04F+191]

2024-10-06 18:51:51.179 | ERROR    | __main__:main:215 - Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/AIHawk_AIHawk_automatic_job_application/blob/main/readme.md#configuration

**Comment by mcwebdev** [comment]
you cant have running chrome instances when you start the script.

**Comment by srtandon** [comment]
Yea I had this problem. If closing chrome doesn't solve the issue check your paths to the chrome application. You might have to set it explicitly, and the user data directory as well. I was running in WSL and just downloaded the linux version of chrome and it worked.

**Comment by Desouki27** [comment]
> Yea I had this problem. If closing chrome doesn't solve the issue check your paths to the chrome application. You might have to set it explicitly, and the user data directory as well. I was running in WSL and just downloaded the linux version of chrome and it worked.

i'm running it on windows, for some reason it worked running it from cmd but if i try running it from powershell i get that error
