### ISSUE TITLE
[HELP WANTED]: Script doesn't output any response or error after execution on MacOS

### ISSUE THREAD

**Issue by swingcake** [feder-cr/Auto_Jobs_Applier_AIHawk#487]
### Issue description

After following all the instructions as stated in the readme, when I run the program - I get nothing. No errors, no new window pop-up, just nothing.

<img width="573" alt="Screenshot 2024-10-07 at 12 13 46 PM" src="https://github.com/user-attachments/assets/ed75a1b7-99f1-4d1b-b418-c43752dbe496">

What could be the issue?

Thanks in advance!

### Specific tasks

Program execution

### Additional context

Running on MacOS

**Comment by swingcake** [comment]
I was able to fix this with pyenv. There seems to be an issue with python shipped with Xcode tools in macOS.

**Comment by gagandeep7717** [comment]
I am seeing the same issue, per previous comment, I do have python environment running. 

```
~/pm-automata/Auto_Jobs_Applier_AIHawk-main --> which python
/Users/gagandeep/pm-automata/Auto_Jobs_Applier_AIHawk-main/virtual/bin/python

~/pm-automata/Auto_Jobs_Applier_AIHawk-main --> python --version
Python 3.9.6

 ~/pm-automata/Auto_Jobs_Applier_AIHawk-main --> python main.py
```

**Comment by swingcake** [comment]
Try pyenv, the python you're seeing is the one shipped with xcode tools in macos

**Comment by karansapolia** [comment]
Mind sharing how you did that @swingcake? I'm new to Python and tried setting the pyenv python version globally and locally, but `which python` now returns:
```
✗ which python
/Users/abcd/opt/anaconda3/bin/python
```
