### ISSUE TITLE
[FEATURE]: Whitelist 

### ISSUE THREAD

**Issue by mcwebdev** [feder-cr/Auto_Jobs_Applier_AIHawk#495]
### Feature summary

A whitelist for the config.yaml.

### Feature description

A whitelist to only apply to jobs with the search term in the title. For example searching "Angular Developer" returns several jobs that dont have angular in the title, and are not angular developer jobs. It should skip any jobs without the search string in the title. 

I also do not think the blacklist works because it applies to jobs with matched blacklist stings.

### Motivation

specificity

### Alternatives considered

I tried filtering out several jobs using the blacklist, but it is not working

**Comment by queukat** [comment]
blacklist fixed in https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/473
