### ISSUE TITLE
[BUG]: requirements.txt not fully downloading

### ISSUE THREAD

**Issue by Gleiser18** [feder-cr/Auto_Jobs_Applier_AIHawk#497]
### Branch

None

### Additional context

(virtual) (base) ilans-MBP:Auto_Jobs_Applier_AIHawk ilangleiser$ pip install -r requirements.txt
Collecting git+https://github.com/feder-cr/lib_resume_builder_AIHawk.git (from -r requirements.txt (line 2))
  Cloning https://github.com/feder-cr/lib_resume_builder_AIHawk.git to /private/var/folders/dh/rvzf31v57ln0cpl8_th4k2740000gn/T/pip-req-build-3e7s9tni
  Running command git clone --filter=blob:none --quiet https://github.com/feder-cr/lib_resume_builder_AIHawk.git /private/var/folders/dh/rvzf31v57ln0cpl8_th4k2740000gn/T/pip-req-build-3e7s9tni
  Resolved https://github.com/feder-cr/lib_resume_builder_AIHawk.git to commit d4224a9fde34c95cce391651b920f6c94eade5d3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click (from -r requirements.txt (line 1))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting httpx~=0.27.2 (from -r requirements.txt (line 3))
  Using cached httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)
Collecting inputimeout==1.0.4 (from -r requirements.txt (line 4))
  Using cached inputimeout-1.0.4-py3-none-any.whl.metadata (2.2 kB)
Collecting jsonschema==4.23.0 (from -r requirements.txt (line 5))
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting jsonschema-specifications==2023.12.1 (from -r requirements.txt (line 6))
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain==0.2.11 (from -r requirements.txt (line 7))
  Using cached langchain-0.2.11-py3-none-any.whl.metadata (7.1 kB)
Collecting langchain-anthropic (from -r requirements.txt (line 8))
  Using cached langchain_anthropic-0.1.23-py3-none-any.whl.metadata (2.2 kB)
Collecting langchain-huggingface (from -r requirements.txt (line 9))
  Using cached langchain_huggingface-0.0.3-py3-none-any.whl.metadata (1.2 kB)
Collecting langchain-community==0.2.10 (from -r requirements.txt (line 10))
  Using cached langchain_community-0.2.10-py3-none-any.whl.metadata (2.7 kB)
Collecting langchain-core===0.2.36 (from -r requirements.txt (line 11))
  Using cached langchain_core-0.2.36-py3-none-any.whl.metadata (6.2 kB)
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.9,<4.0; 0.0.10rc0 Requires-Python >=3.9,<4.0; 0.0.11 Requires-Python >=3.9,<4.0; 0.0.1rc0 Requires-Python >=3.9,<4.0; 0.0.2 Requires-Python >=3.9,<4.0; 0.0.3 Requires-Python >=3.9,<4.0; 0.0.4 Requires-Python >=3.9,<4.0; 0.0.5 Requires-Python >=3.9,<4.0; 0.0.6 Requires-Python >=3.9,<4.0; 0.0.7 Requires-Python >=3.9,<4.0; 0.0.8 Requires-Python >=3.9,<4.0; 0.0.9 Requires-Python >=3.9,<4.0; 0.1.0 Requires-Python <4.0,>=3.9; 0.1.0.dev1 Requires-Python <4.0,>=3.9; 0.2.0 Requires-Python <4.0,>=3.9; 0.2.0.dev0 Requires-Python <4.0,>=3.9; 0.2.0.dev1 Requires-Python <4.0,>=3.9; 0.2.1 Requires-Python <4.0,>=3.9; 0.2.2 Requires-Python <4.0,>=3.9; 0.2.3 Requires-Python <4.0,>=3.9; 0.3.0 Requires-Python <4.0,>=3.9; 0.3.0.dev1 Requires-Python <4.0,>=3.9; 0.3.0.dev2 Requires-Python <4.0,>=3.9; 0.3.0.dev3 Requires-Python <4.0,>=3.9; 0.3.0.dev4 Requires-Python <4.0,>=3.9; 0.3.0.dev5 Requires-Python <4.0,>=3.9; 0.3.1 Requires-Python <4.0,>=3.9; 0.3.2 Requires-Python <4.0,>=3.9; 0.3.3 Requires-Python <4.0,>=3.9; 0.3.4 Requires-Python <4.0,>=3.9; 0.3.5 Requires-Python <4.0,>=3.9; 0.3.6 Requires-Python <4.0,>=3.9; 0.3.7 Requires-Python <4.0,>=3.9; 0.3.8 Requires-Python <4.0,>=3.9; 0.3.9 Requires-Python <4.0,>=3.9; 1.0.1 Requires-Python <4.0,>=3.9; 1.0.10 Requires-Python <4.0,>=3.9; 1.0.2 Requires-Python <4.0,>=3.9; 1.0.3 Requires-Python <4.0,>=3.9; 1.0.4 Requires-Python <4.0,>=3.9; 1.0.5 Requires-Python <4.0,>=3.9; 1.0.6 Requires-Python <4.0,>=3.9; 1.0.7 Requires-Python <4.0,>=3.9; 1.0.8 Requires-Python <4.0,>=3.9; 1.0.9 Requires-Python <4.0,>=3.9; 2.0.0 Requires-Python <4.0,>=3.9; 2.0.0.dev1 Requires-Python <4.0,>=3.9; 2.0.1 Requires-Python <4.0,>=3.9; 2024.10.1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement langchain-google-genai==1.0.10 (from versions: none)
ERROR: No matching distribution found for langchain-google-genai==1.0.10
(virtual) (base) ilans-MBP:Auto_Jobs_Applier_AIHawk ilangleiser$

**Comment by TaylorOD** [comment]
What version of python are you using? If you install python without specifying a version, the latest version (3.13) will be installed, which might not be compatible with the other dependencies.
