### ISSUE TITLE
[HELP WANTED]: Unable to download requirements.txt due to conflicting dependencies

### ISSUE THREAD

**Issue by hags50** [feder-cr/Auto_Jobs_Applier_AIHawk#498]
### Issue description

ERROR: Cannot install -r requirements.txt (line 10), -r requirements.txt (line 12), -r requirements.txt (line 13), -r requirements.txt (line 14), -r requirements.txt (line 15), -r requirements.txt (line 2), -r requirements.txt (line 7), -r requirements.txt (line 8) and langchain-core===0.2.36 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.2.3 depends on langchain-core<0.4.0 and >=0.3.9
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.2.1 depends on langchain-core<0.4.0 and >=0.3.1
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.2.0 depends on langchain-core<0.4.0 and >=0.3.0
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.11 depends on langchain-core<0.2.0 and >=0.1.43
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.10 depends on langchain-core<0.2.0 and >=0.1.43
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.9 depends on langchain-core<0.2.0 and >=0.1.43
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.8 depends on langchain-core<0.2.0 and >=0.1.42
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.7 depends on langchain-core<0.2.0 and >=0.1.41
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.6 depends on langchain-core<0.2.0 and >=0.1.33
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.5 depends on langchain-core<0.2.0 and >=0.1.33
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.4 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.3 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.2 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.1 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.0 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core===0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.0.2 depends on langchain-core<0.2 and >=0.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Additional context

I even tried installing using  --no-deps, but that led to ERROR: Failed building wheel for Levenshtein

**Comment by abdulrafe** [comment]
I am facing the same the issue.

**Comment by hags50** [comment]
i kinda figured out why its not working for me. i have windows 11, it will work with windows 10
