### ISSUE TITLE
[BUG]: <ChromeDriver only supports Chrome version 114>

### ISSUE THREAD

**Issue by tyroniuz** [feder-cr/Auto_Jobs_Applier_AIHawk#499]
### Describe the bug

opens the interface then closes almost instantly

### Steps to reproduce

I have this issue with both newer Chrome 129 and also older versions... havent been able to locate chrome 114 download anywhere to test with

2024-10-09 01:16:45.504 | ERROR    | __main__:main:213 - Runtime error: Error running the bot: Failed to initialize browser: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 104.0.5112.102 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x003AA813+48355]
        (No symbol) [0x0033C4B1]
        (No symbol) [0x00245358]
        (No symbol) [0x002661AC]
        (No symbol) [0x00261EF3]
        (No symbol) [0x00260579]
        (No symbol) [0x00290C55]
        (No symbol) [0x0029093C]
        (No symbol) [0x0028A536]
        (No symbol) [0x002682DC]
        (No symbol) [0x002693DD]
        GetHandleVerifier [0x0060AABD+2539405]
        GetHandleVerifier [0x0064A78F+2800735]
        GetHandleVerifier [0x0064456C+2775612]
        GetHandleVerifier [0x004351E0+616112]
        (No symbol) [0x00345F8C]
        (No symbol) [0x00342328]
        (No symbol) [0x0034240B]
        (No symbol) [0x00334FF7]
        BaseThreadInitThunk [0x76C0FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77EB809E+286]
        RtlGetAppContainerNamedObjectPath [0x77EB806E+238]

2024-10-09 01:16:45.505 | ERROR    | __main__:main:215 - Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/AIHawk_AIHawk_automatic_job_application/blob/main/readme.md#configuration

### Expected behavior

launch correctly

### Actual behavior

Closes interface almost immediately

### Branch

main

### Python version

3.11.9

### LLM Used

ollama 

### Model used

3,1

**Comment by mcwebdev** [comment]
You have a background chrome process running. If you cant find the process running in task manager, reboot your machine.

**Comment by tyroniuz** [comment]
Ok so I did end up finally finding the 114 chrome version and yes I must have had something running within chrome/extensions that had hung up on my machine - after a few attempts at removing and reinstalling chrome I was able to get it to launch properly  - Thank you so much for all the work you do on this!!
