### ISSUE TITLE
[BUG]: Error while installing requirements.txt dependencies

### ISSUE THREAD

**Issue by Ilkham-Karimzhan** [feder-cr/Auto_Jobs_Applier_AIHawk#500]
### Describe the bug

Afeter running pip install -r "requirements.txt" get some errors.

### Steps to reproduce

OS: Windows 10
Python: 3.13.0
Tried on VS Code with bash if that matters.

1. Go throw all previous steps in installation.
2. pip install -r requirements.txt - throws this

`Collecting git+https://github.com/feder-cr/lib_resume_builder_AIHawk.git (from -r requirements.txt (line 2))
  Cloning https://github.com/feder-cr/lib_resume_builder_AIHawk.git to c:\users\avrora\appdata\local\temp\pip-req-build-4j8pbebt
  Running command git clone --filter=blob:none --quiet https://github.com/feder-cr/lib_resume_builder_AIHawk.git 'C:\Users\Avrora\AppData\Local\Temp\pip-req-build-4j8pbebt'
  Resolved https://github.com/feder-cr/lib_resume_builder_AIHawk.git to commit d4224a9fde34c95cce391651b920f6c94eade5d3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click (from -r requirements.txt (line 1))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting httpx~=0.27.2 (from -r requirements.txt (line 3))
  Using cached httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)
Collecting inputimeout==1.0.4 (from -r requirements.txt (line 4))
  Using cached inputimeout-1.0.4-py3-none-any.whl.metadata (2.2 kB)
Collecting jsonschema==4.23.0 (from -r requirements.txt (line 5))
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting jsonschema-specifications==2023.12.1 (from -r requirements.txt (line 6))
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain==0.2.11 (from -r requirements.txt (line 7))
  Using cached langchain-0.2.11-py3-none-any.whl.metadata (7.1 kB)
Collecting langchain-anthropic (from -r requirements.txt (line 8))
  Using cached langchain_anthropic-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Collecting langchain-huggingface (from -r requirements.txt (line 9))
  Using cached langchain_huggingface-0.1.0-py3-none-any.whl.metadata (1.3 kB)
Collecting langchain-community==0.2.10 (from -r requirements.txt (line 10))
  Using cached langchain_community-0.2.10-py3-none-any.whl.metadata (2.7 kB)
Collecting langchain-core===0.2.36 (from -r requirements.txt (line 11))
  Using cached langchain_core-0.2.36-py3-none-any.whl.metadata (6.2 kB)
Collecting langchain-google-genai==1.0.10 (from -r requirements.txt (line 12))
  Using cached langchain_google_genai-1.0.10-py3-none-any.whl.metadata (3.8 kB)
Collecting langchain-ollama==0.1.3 (from -r requirements.txt (line 13))
  Using cached langchain_ollama-0.1.3-py3-none-any.whl.metadata (1.8 kB)
Collecting langchain-openai==0.1.17 (from -r requirements.txt (line 14))
  Using cached langchain_openai-0.1.17-py3-none-any.whl.metadata (2.5 kB)
Collecting langchain-text-splitters==0.2.2 (from -r requirements.txt (line 15))
  Using cached langchain_text_splitters-0.2.2-py3-none-any.whl.metadata (2.1 kB)
Collecting langsmith==0.1.93 (from -r requirements.txt (line 16))
  Using cached langsmith-0.1.93-py3-none-any.whl.metadata (13 kB)
Collecting Levenshtein==0.25.1 (from -r requirements.txt (line 17))
  Using cached Levenshtein-0.25.1.tar.gz (149 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting loguru==0.7.2 (from -r requirements.txt (line 18))
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting openai==1.37.1 (from -r requirements.txt (line 19))
  Using cached openai-1.37.1-py3-none-any.whl.metadata (22 kB)
Collecting pdfminer.six==20221105 (from -r requirements.txt (line 20))
  Using cached pdfminer.six-20221105-py3-none-any.whl.metadata (4.0 kB)
Collecting pytest>=8.3.3 (from -r requirements.txt (line 21))
  Using cached pytest-8.3.3-py3-none-any.whl.metadata (7.5 kB)
Collecting python-dotenv~=1.0.1 (from -r requirements.txt (line 22))
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting PyYAML~=6.0.2 (from -r requirements.txt (line 23))
  Using cached PyYAML-6.0.2-cp313-cp313-win_amd64.whl.metadata (2.1 kB)
Collecting regex==2024.7.24 (from -r requirements.txt (line 24))
  Using cached regex-2024.7.24.tar.gz (393 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting reportlab==4.2.2 (from -r requirements.txt (line 25))
  Using cached reportlab-4.2.2-py3-none-any.whl.metadata (1.4 kB)
Collecting selenium==4.9.1 (from -r requirements.txt (line 26))
  Using cached selenium-4.9.1-py3-none-any.whl.metadata (7.2 kB)
Collecting webdriver-manager==4.0.2 (from -r requirements.txt (line 27))
  Using cached webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting pytest-mock (from -r requirements.txt (line 29))
  Using cached pytest_mock-3.14.0-py3-none-any.whl.metadata (3.8 kB)
Collecting pytest-cov (from -r requirements.txt (line 30))
  Using cached pytest_cov-5.0.0-py3-none-any.whl.metadata (27 kB)
Collecting attrs>=22.2.0 (from jsonschema==4.23.0->-r requirements.txt (line 5))
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting referencing>=0.28.4 (from jsonschema==4.23.0->-r requirements.txt (line 5))
  Using cached referencing-0.35.1-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema==4.23.0->-r requirements.txt (line 5))
  Using cached rpds_py-0.20.0-cp313-none-win_amd64.whl.metadata (4.2 kB)
Collecting SQLAlchemy<3,>=1.4 (from langchain==0.2.11->-r requirements.txt (line 7))
  Using cached SQLAlchemy-2.0.35-py3-none-any.whl.metadata (9.6 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain==0.2.11->-r requirements.txt (line 7))
  Using cached aiohttp-3.10.9-cp313-cp313-win_amd64.whl.metadata (7.8 kB)
Collecting numpy<2.0.0,>=1.26.0 (from langchain==0.2.11->-r requirements.txt (line 7))
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + C:\Users\Avrora\Documents\own\Auto_Jobs_Applier_AIHawk\virtual\Scripts\python.exe C:\Users\Avrora\AppData\Local\Temp\pip-install-wxdj6ct_\numpy_a0348120f36b45e2a82a92f6fb95c2ac\v
endored-meson\meson\meson.py setup C:\Users\Avrora\AppData\Local\Temp\pip-install-wxdj6ct_\numpy_a0348120f36b45e2a82a92f6fb95c2ac C:\Users\Avrora\AppData\Local\Temp\pip-install-wxdj6ct_\
numpy_a0348120f36b45e2a82a92f6fb95c2ac\.mesonpy-fw_925sc -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Avrora\AppData\Local\Temp\pip-install-wxdj6ct_\numpy_a0348120f36b45e2a82a92f6fb95c2ac\.mesonpy-fw_925sc\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\Avrora\AppData\Local\Temp\pip-install-wxdj6ct_\numpy_a0348120f36b45e2a82a92f6fb95c2ac
      Build dir: C:\Users\Avrora\AppData\Local\Temp\pip-install-wxdj6ct_\numpy_a0348120f36b45e2a82a92f6fb95c2ac\.mesonpy-fw_925sc
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] Не удается найти указанный файл"
      Running `cl /?` gave "[WinError 2] Не удается найти указанный файл"
      Running `cc --version` gave "[WinError 2] Не удается найти указанный файл"
      Running `gcc --version` gave "[WinError 2] Не удается найти указанный файл"
      Running `clang --version` gave "[WinError 2] Не удается найти указанный файл"
      Running `clang-cl /?` gave "[WinError 2] Не удается найти указанный файл"
      Running `pgcc --version` gave "[WinError 2] Не удается найти указанный файл"

      A full log can be found at C:\Users\Avrora\AppData\Local\Temp\pip-install-wxdj6ct_\numpy_a0348120f36b45e2a82a92f6fb95c2ac\.mesonpy-fw_925sc\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(virtual) `

### Branch

None

**Comment by mcwebdev** [comment]
you need to run cmd as administrator.

**Comment by Ilkham-Karimzhan** [comment]
> you need to run cmd as administrator.

Run on PowerShell and windows command panel, getting same issue. 
And for some reasons can't use source command, only after opening project in VS Code.

**Comment by RichP-fr** [comment]
You need to install Python 3.12.5. After I uninstalled Python 3.13.0 and installed Python 3.12.5, this command worked.

**Comment by BhargavSushant** [comment]
@
I agree with @RichP-fr 

## Issue: Python3.13 exhibits conflicting dependencies in langchain modules. 

> ### Steps to reproduce

> > pip install -r requirements 

## Resolution: No Resolution so far as per langchain docs and python command's output. 

## Workaround: use python 3.12 instead using virtualenv 

1. Install python 3.12
2. Install virtualenv
    `pip install virtualenv`
3. Create virtual environment using virtualenv 

- mac / linux
`source virtual/bin/activate`

- windows
`virtualenv -p python3.12 virtual`
 
4. As an administrator install requirements.
` pip install -r requirements `

@feder-cr @Ilkham-Karimzhan

**Comment by BhargavSushant** [comment]
@Ilkham-Karimzhan 

> > you need to run cmd as administrator.
> 
> Run on PowerShell and windows command panel, getting same issue. And for some reasons can't use source command, only after opening project in VS Code.

@Ilkham-Karimzhan You don't need to source in windows

**Comment by TaylorOD** [comment]
+1 to the others mentioning python versioning. 3.13 will cause conflicts.

**Comment by feder-cr** [comment]
@BhargavSushant @mcwebdev @Ilkham-Karimzhan @RichP-fr @MuilaerteJunior join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
