### ISSUE TITLE
[BUG]: Applying to jobs in "more jobs" section when the search results for the jobs are 0 (zero)

### ISSUE THREAD

**Issue by swingcake** [feder-cr/Auto_Jobs_Applier_AIHawk#507]
### Describe the bug

The bot continues applying to jobs in the "more jobs" section which are mostly irrelevant and also do not follow rules like "remote" and "job titles/positions"

### Expected behavior

Try another job title from the list of titles provided if results for a particular position is 0 (no jobs available)

### Actual behavior

Keeps applying to jobs in "more jobs for you" section.

### Branch

None

### LLM Used

OpenAI

### Model used

gpt-4o-mini

### Additional context

Happens arbitrarily, not always.

**Comment by sodamaroons** [comment]
1

**Comment by feder-cr** [comment]
@swingcake join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
