### ISSUE TITLE
[BUG]: It's applying for Canada position when your config is US alone

### ISSUE THREAD

**Issue by surapuramakhil** [feder-cr/Auto_Jobs_Applier_AIHawk#508]
### Branch

None

**Comment by grunsab** [comment]
Hi,

Do you have an example job that was applied for in Canada. I looked at the code and it seems that it should only apply to jobs in that specific location, as long as LinkedIn filtering is working correctly.

**Comment by surapuramakhil** [comment]
@grunsab there were a lot of, my recent 20+ rejections were in this category. not sure how many it has applied.
An example job - https://www.linkedin.com/jobs-guest/jobs/view/4040430646/

**Comment by surapuramakhil** [comment]
I don't think it's a bug, I have run this with different config which has Canada long back.
