### ISSUE TITLE
[HELP WANTED]: I run the python main.py it run for 30 sec and then nothing showed up, then it went back to normal typing prompt

### ISSUE THREAD

**Issue by Aniket22156** [feder-cr/Auto_Jobs_Applier_AIHawk#513]
### Issue description

(virtual) (base) aniketsharma@Anikets-MacBook-Pro Auto_Jobs_Applier_AIHawk % python main.py
(virtual) (base) aniketsharma@Anikets-MacBook-Pro Auto_Jobs_Applier_AIHawk % python main.py

I am using a macbook pro 14inch with M1 pro chip, i ran python main.py and nothing worked, it went to normal typing prompt, i also checked the usage of the API but there is no usage. where i am getting wrong?

**Comment by jcl0251** [comment]
I went into main.py and I commented out the "Supress stderr" line and then just went ahead and fixed the error it was giving me. 
The error was because my python version was not up to date. Try this out. It should be the first line of code after the imports.

**Comment by Aniket22156** [comment]
Traceback (most recent call last):
  File "/Users/aniketsharma/Documents/JOB/Auto_Jobs_Applier_AIHawk/main.py", line 117, in <module>
    class FileManager:
  File "/Users/aniketsharma/Documents/JOB/Auto_Jobs_Applier_AIHawk/main.py", line 138, in FileManager
    def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path) -> dict:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

I got a new error, do you also got this

**Comment by Aniket22156** [comment]
> I went into main.py and I commented out the "Supress stderr" line and then just went ahead and fixed the error it was giving me. The error was because my python version was not up to date. Try this out. It should be the first line of code after the imports.

Traceback (most recent call last):
File "/Users/aniketsharma/Documents/JOB/Auto_Jobs_Applier_AIHawk/main.py", line 117, in
class FileManager:
File "/Users/aniketsharma/Documents/JOB/Auto_Jobs_Applier_AIHawk/main.py", line 138, in FileManager
def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path) -> dict:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

I got a new error, do you also got this

**Comment by jcl0251** [comment]
Yeah, that looks like the exact error I got. Looks like removing the stderr suppress line worked. 

Next, go into main.py and go to line 138. Should be around there. This is what you want. You're switching to "Optional[Path]" because I think its the same issue of python version. You can probably confirm this by doing "python --version".
Here is the fix that worked for me before I updated:


def file_paths_to_dict(resume_file: Optional[Path], plain_text_resume_file: Path) -> dict:

**Comment by Aniket22156** [comment]
> Yeah, that looks like the exact error I got. Looks like removing the stderr suppress line worked.
> 
> Next, go into main.py and go to line 138. Should be around there. This is what you want. You're switching to "Optional[Path]" because I think its the same issue of python version. You can probably confirm this by doing "python --version". Here is the fix that worked for me before I updated:
> 
> def file_paths_to_dict(resume_file: Optional[Path], plain_text_resume_file: Path) -> dict:
> 
> Edit: Also, this requires "from typing import Optional" import. I forgot to add.

i did that and thanks that worked very well but now i got new error, 
Invoking OpenAI API
2024-10-12 10:22:39.894 | ERROR    | src.llm.llm_manager:__call__:293 - Unexpected error occurred: Error code: 403 - {'error': {'message': 'Project `proj_nGfseop8KjtaI5YmoIT8OXv0` does not have access to model `gpt-4o`', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-10-12 10:22:39.895 | INFO     | src.llm.llm_manager:__call__:294 - Waiting for 30 seconds before retrying due to an unexpected error. 
Do you also get that let me know and what was the solution

**Comment by jcl0251** [comment]
I did not, but that looks to me like you haven't properly set up your API key. 

Do you have an Open AI API key? With the paid credits and such? Should only need 5 dollars, at least to start with. Unless you're using another LLM, then it would obviously be a different API.

**Comment by Aniket22156** [comment]
> I did not, but that looks to me like you haven't properly set up your API key.
> 
> Do you have an Open AI API key? With the paid credits and such? Should only need 5 dollars, at least to start with. Unless you're using another LLM, then it would obviously be a different API.

Yes i have the api key and i already paid 5$ but i made the second api key because i thought it was not working, can you let me know where to put the API key

**Comment by jcl0251** [comment]
It goes into data_folder/secrets.yaml. Make sure you replace the placeholder key and careful with the beginning and end quotes. I don't think you should need the key anywhere else.

**Comment by Aniket22156** [comment]
> It goes into data_folder/secrets.yaml. Make sure you replace the placeholder key and careful with the beginning and end quotes. I don't think you should need the key anywhere else.

i already pasted it there, but still it doesn't work, do you need a upgrade account for openai to use the API properly or you just need that 5$, btw can you let me know your telegram id or something else where i can contact you, it's easy to talk there instead of this comment

**Comment by jcl0251** [comment]
Yeah, do you have discord?

**Comment by Aniket22156** [comment]
> Yeah, do you have discord?
ya.. but didn't used it much so i have to find it's password, but i think i found the problem, in the project page where i add the allowed model, i only included dall-e 3 and not any other so i think i need to add gpt-4o in that

**Comment by jcl0251** [comment]
Ahhh that could be it. Did you also make sure that the end of config.yaml is correct? with the model information

**Comment by Aniket22156** [comment]
Yes I changed it

**Comment by Aniket22156** [comment]
> Ahhh that could be it. Did you also make sure that the end of config.yaml is correct? with the model information

Hey can you give me your discord id so i can add you, i wanted to talk about some others things also

**Comment by jcl0251** [comment]
Yeah, add me. @bryler1

**Comment by feder-cr** [comment]
@Aniket22156  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
