### ISSUE TITLE
[HELP WANTED]: <Chrome version>

### ISSUE THREAD

**Issue by Ravel226** [feder-cr/Auto_Jobs_Applier_AIHawk#515]
### Issue description

2024-10-11 21:04:17.904 | ERROR    | __main__:main:213 - Runtime error: Error running the bot: Failed to initialize browser: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 129.0.6668.90 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00ADA813+48355]
        (No symbol) [0x00A6C4B1]
        (No symbol) [0x00975358]
        (No symbol) [0x009961AC]
        (No symbol) [0x00991EF3]
        (No symbol) [0x00990579]
        (No symbol) [0x009C0C55]
        (No symbol) [0x009C093C]
        (No symbol) [0x009BA536]
        (No symbol) [0x009982DC]
        (No symbol) [0x009993DD]
        GetHandleVerifier [0x00D3AABD+2539405]
        GetHandleVerifier [0x00D7A78F+2800735]
        GetHandleVerifier [0x00D7456C+2775612]
        GetHandleVerifier [0x00B651E0+616112]
        (No symbol) [0x00A75F8C]
        (No symbol) [0x00A72328]
        (No symbol) [0x00A7240B]
        (No symbol) [0x00A64FF7]
        BaseThreadInitThunk [0x76FE7BA9+25]
        RtlInitializeExceptionChain [0x7785C0CB+107]
        RtlClearBits [0x7785C04F+191]

2024-10-11 21:04:17.906 | ERROR    | __main__:main:215 - Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/AIHawk_AIHawk_automatic_job_application/blob/main/readme.md#configuration

**Comment by d-p35** [comment]
hey were you able to resolve this?

**Comment by Ravel226** [comment]
> hey were you able to resolve this?

Yup
Just download chrome version 114 and desable chrome auto-update in services. Here is the link for downloading. You're free to trust it or not:

https://www.filepuma.com/download/google_chrome_64bit_114.0.5735.199-35569/
