### ISSUE TITLE
type object 'FacadeManager' has no attribute 'StyleManager'

### ISSUE THREAD

**Issue by mellahysf** [feder-cr/Auto_Jobs_Applier_AIHawk#528]
### Steps to reproduce

$ python main.py
2024-10-13 20:35:55.348 | ERROR    | __main__:main:210 - Runtime error: Error running the bot: type object 'FacadeManager' has no attribute 'StyleManager'

### Branch

None

### Additional context

$ python main.py
2024-10-13 20:35:55.348 | ERROR    | __main__:main:210 - Runtime error: Error running the bot: type object 'FacadeManager' has no attribute 'StyleManager'

**Comment by manhphim** [comment]
Here's how I fixed it: 

In `main.py:11`, replace to `from lib_resume_builder_AIHawk import Resume, FacadeManager, ResumeGenerator, StyleManager`

In `main.py:161`, replace to `style_manager = StyleManager()`

Hope this help

**Comment by SailingSF** [comment]
I had the same error and this fixed it. 

> Here's how I fixed it:
> 
> In `main.py:11`, replace to `from lib_resume_builder_AIHawk import Resume, FacadeManager, ResumeGenerator, StyleManager`
> 
> In `main.py:161`, replace to `style_manager = StyleManager()`
> 
> Hope this help

**Comment by mellahysf** [comment]
@manhphim it works. Thank you. Better to open a PR for this to be resolved.
