### ISSUE TITLE
[BUG]: Unexpected error while parsing YAML

### ISSUE THREAD

**Issue by yention** [feder-cr/Auto_Jobs_Applier_AIHawk#541]
### Describe the bug

clone from the master, changes exactly as described in the readme

### Steps to reproduce

clone from the master, changes exactly as described in the readme
macOS m1

Runtime error: Error running the bot: Unexpected error while parsing YAML: 7 validation errors for Resume
personal_information.zip_code
  String should have at most 10 characters [type=string_too_long, input_value='[Your zip code]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/string_too_long
personal_information.email
  value is not a valid email address: An email address must have an @-sign. [type=value_error, input_value='[Your Email Address]', input_type=str]
personal_information.github
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Your GitHub Profile URL]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
personal_information.linkedin
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Your LinkedIn Profile URL]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
education_details.0.year_of_completion
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='[Year of Completion]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing
projects.0.link
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Project Link]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
projects.1.link
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Project Link]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing

### Branch

main

### Python version

3.12

### LLM Used

gpt

### Model used

gpt-4o-mini

**Comment by yention** [comment]
personal_information:
  name: "Alex"
  surname: "zzz"
  date_of_birth: "03/02/1990"
  country: "United States of America"
  city: "Dallas"
  zip_code: "76179"
  address: "main st"
  phone_prefix: "+1"
  phone: "123456789"
  email: "qaqaqa@gmail.com"
  github: "https://github.com/lol"
  linkedin: "https://www.linkedin.com/in/mylink/"

**Comment by AliLotfi92** [comment]
I guess you have your personal info in "data_folder_example". it should be in "data_folder"

**Comment by Tianci278** [comment]
I had the same issue, and I realised I have some sections in the plain_text_resume.yaml are left empty, I commented them out and now it works.

**Comment by BytePlanetWei** [comment]
> I had the same issue, and I realised I have some sections in the plain_text_resume.yaml are left empty, I commented them out and now it works.

I commented them all and still not working...

**Comment by AliLotfi92** [comment]
try: https://www.yamllint.com/

it helps you to find syntax error in your yaml file.

**Comment by BytePlanetWei** [comment]
> try: https://www.yamllint.com/
> 
> it helps you to find syntax error in your yaml file.

Thank you I checked my file is valid, but still have errors. 

2024-10-15 17:32:40.812 | ERROR    | __main__:main:210 - Runtime error: Error running the bot: Unexpected error while parsing YAML: 3 validation errors for Resume
personal_information.email
  value is not a valid email address: The email address contains invalid characters before the @-sign: '['. [type=value_error, input_value='[myemail@hotmail.com]', input_type=str]
personal_information.linkedin
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[https://www.linkedin.com/in/mylink/]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
education_details.0.year_of_completion
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='[2019]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing

**Comment by qadir1020** [comment]
go to the data_folder and add values to the keys in plian_text_resume.yaml file

**Comment by Malda-Sh** [comment]
I am facing the following issue:
 

> from webdriver_manager.core.file_manager import File
ImportError: cannot import name 'File' from partially initialized module 'webdriver_manager.core.file_manager' (most likely due to a circular import) `(C:\Users\xxx\Auto_Jobs_Applier_AIHawk\virtual\Lib\site-packages\webdriver_manager\core\file_manager.py)> 

How to solve this?

**Comment by Dobrzinska** [comment]
I have similar issue. 2024-11-02 20:11:25.130 | ERROR    | __main__:main:219 - Runtime error: Error running the bot: Unexpected error while parsing YAML: 7 validation errors for Resume
personal_information.zip_code
  String should have at most 10 characters [type=string_too_long, input_value='[Your zip code]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/string_too_long
personal_information.email
  value is not a valid email address: An email address must have an @-sign. [type=value_error, input_value='[Your Email Address]', input_type=str]
personal_information.github
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Your GitHub Profile URL]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
personal_information.linkedin
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Your LinkedIn Profile URL]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
education_details.0.year_of_completion
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='[Year of Completion]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing
projects.0.link
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Project Link]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
projects.1.link
  Input should be a valid URL, a relative URL without a base [type=url_parsing, input_value='[Project Link]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
I have checked YAML. It's valid. Typing in an email, and changing, the postcode does not solve the problem.
