### ISSUE TITLE
[FEATURE]: Apply to a single job given a URL

### ISSUE THREAD

**Issue by clone45** [feder-cr/Auto_Jobs_Applier_AIHawk#542]
### Feature summary

Ability to apply to a job without needing to run the job search

### Feature description

Hello!  Would it be possible to add a command line flag, such as 

`@click.option('--job-url', type=str, help="URL of the single job to apply to")`

Which would apply to the specified job only?

### Motivation

I have a workflow that collects and rates jobs already.  I'd love to integrate Auto_Jobs_Applier_AIHawk into my workflow specifically for applying to jobs.

### Alternatives considered

Another solution could be to add job ratings to Auto_Jobs_Applier_AIHawk.  Send the resume and job description to an AI to get a rating between 1 and 10, given rating instructions available in the data_folder.  Allow the user to set a rating threshold, and only apply to jobs that achieve a rating above the given threshold.

**Comment by feder-cr** [comment]
@clone45 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
