### ISSUE TITLE
[FEATURE]: AIHawk working with another language other than English

### ISSUE THREAD

**Issue by stefanoolla** [feder-cr/Auto_Jobs_Applier_AIHawk#561]
### Feature summary

Switching from English context and account to another language

### Feature description

It would be great if AIHawk could work with accounts and job offers in different languages from non-english speaking countries.

### Motivation

I'm based in Italy and unfortunately in this context there's no use for this wonderful app

### Alternatives considered

I'm aware the introduction explicitly says that the accounts must be in English for the bot to work.

I was wondering if it would all come down to translating the prompts (and perhaps making adjustments in order to better localize them), or if it would need deeper intervention in the code.

**Comment by feder-cr** [comment]
@stefanoolla join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
