### ISSUE TITLE
[FEATURE]: Answer 0 years of work experiece unless user writes higher in answers.json

### ISSUE THREAD

**Issue by sloganking** [feder-cr/Auto_Jobs_Applier_AIHawk#563]
### Feature summary

When asked about years of experience, the bot should put 0 by default and then remember that answer in answers.json. 

### Feature description

When asked about years of experience, the bot should put 0 by default and then remember that answer in `answers.json`. After a couple hours of job applying, the user can go and correct the years of experience in the `answers.json` file. 

### Motivation

This will allow the bot to apply without making users look better than they actually are.  

### Alternatives considered

The bot could more intelligently determine years of experience from a text or config file, but that's not working right now, and this is a simple fix.

**Comment by TemeSejko** [comment]
How do we setup answers.json? I dont see anything in the hep documents regarding this. Currently, it is putting the wrong experience level for everything for me.

**Comment by sloganking** [comment]
@TemeSejko Currently, `answers.json` saves whatever default value the language model gives to an answer if it has never seen the question before, but when the AI sees that exact string of text as a question again, it will retrieve the value from the `answers.json` file. 

This effectively means that after you run the bot for a while, you can go back and put Real values in your `answers.json` file instead of the values that the bot made up. And then, when the bot encounters that exact same question again, it will give the answer that you put in `answers.json`.
