### ISSUE TITLE
[BUG]: Company specific answer messages saved in answers.json

### ISSUE THREAD

**Issue by sloganking** [feder-cr/Auto_Jobs_Applier_AIHawk#564]
### Describe the bug

Messages tailored to a specific company that may include that company's name get saved in answers.json and reused with different companies they shouldn't be used with. 

### Expected behavior

Messages catering to a specific company should not be saved in Answers.json. 

### Branch

None

**Comment by xTaylorFerg** [comment]
Yeah I've seen this bug as well. I checked my ai output and didn't see the duplicates there. Just started to trace through and find out where it was coming from. Will be taking a look with your clue. Thanks.
