### ISSUE TITLE
[FEATURE]:make it work on windows 11.

### ISSUE THREAD

**Issue by Niassamond1** [feder-cr/Auto_Jobs_Applier_AIHawk#568]
### Feature summary

i'd like to use it on windows 11.

### Feature description

Its simple, i dont have a windows 10 machine, and really loved the project and wanted to test it out!

### Motivation

I Dont have a windows 10 machine

### Alternatives considered

Im trying to install in windows 11 and tried every combination possible but i always get the error : 
 ResolutionImpossible:
  When installing the dependencies. if there's any workaround possible i'd love to know.

**Comment by hexicidal404** [comment]
I have it completely functional on a Windows 11 VM. 

It required a python downgrade, and a requirements text mod.

Python - 3.10.0

langchain==0.2.16
langchain-community==0.2.16
langchain-core==0.2.38
langchain-openai==0.1.20
langchain-text-splitters==0.2.4
langsmith==0.1.93
Levenshtein==0.25.1
openai==1.37.1
regex==2024.7.24
reportlab==4.2.2
selenium==4.9.1
webdriver-manager==4.0.2
click==8.1.7
git+https://github.com/feder-cr/lib_resume_builder_AIHawk.git
linkedin-api==2.3.0
pdfminer.six==20221105
inputimeout==1.0.4
langchain-ollama==0.1.3
langchain-anthropic==0.1.23
langchain-google-genai==1.0.10
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
httpx~=0.27.2
python-dotenv~=1.0.1
PyYAML~=6.0.2
loguru==0.7.2

**Comment by feder-cr** [comment]
@Niassamond1 @hexicidal404  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
