### ISSUE TITLE
[HELP WANTED]: Answers provided are incorrect && experience filter not working 

### ISSUE THREAD

**Issue by Abhishek09yadav** [feder-cr/Auto_Jobs_Applier_AIHawk#586]
### Issue description

**Description:**
I encountered the following issues while using GPT-4O and Gemini bots:

1. **Incorrect Details Filled by the Bot:** 
   - The bot is filling incorrect information in the forms, such as:
     - I do not have Angular experience, but the bot is filling 2 years of experience in Angular (this is not mentioned in my `plain_text_resume.yaml`).
     - My notice period is 0 days, but the bot is filling 2 days.
     - My total experience is 1.4 years, but the bot is filling 4 years.
   
   Based on a suggestion in a previous issue, I changed the temperature from 0.4 to 0.7, but this did not resolve the issue. It seems like the bot is filling details from the job description (JD) rather than my actual data.

2. **Experience Filter Not Working:**
   - The experience filter appears to be malfunctioning. Despite configuring my experience level as follows, the bot is not filtering correctly:

   ```
   experienceLevel:
     internship: true
     entry: true
     associate: false
     mid-senior level: false
     director: false
     executive: false
   ```

Could you please assist in resolving these issues? Let me know if you need any additional information. 

Thank you.

**Comment by sarob** [comment]
update your answers.json file. It is likely the questions are answered incorrectly there. 

you should get about 60-70% success rate after that.

**Comment by ethan-haas** [comment]
To fix experience filter change this line in src/aihawk_job_manager.py:
experience_levels = [str(i + 1) for i, (level, v) in enumerate(parameters.get('experience_level', {}).items()) if
                             v]

to:
experience_levels = [str(i + 1) for i, (level, v) in enumerate(parameters.get('experienceLevel', {}).items()) if
                             v]

Hope this helps! This bug was created several weeks ago when changing the config setup, soon they will update the main to fix this.

**Comment by feder-cr** [comment]
@ethan-haas do a PR request

**Comment by ethan-haas** [comment]
I'm not very familiar with github. I was hoping someone else would do it. @feder-cr

**Comment by Abhishek09yadav** [comment]
Thank you, @ethan-haas and @sarob, for your guidance! Your suggestions resolved the issues successfully. I made the updates, and everything seems to be working smoothly now. I did notice another bug where the bot occasionally fails to fill certain fields, so I'll document this separately with more details and screenshots.
