### ISSUE TITLE
[BUG]: fails to fill up numeric fields 

### ISSUE THREAD

**Issue by akashbilgi** [feder-cr/Auto_Jobs_Applier_AIHawk#596]
### Describe the bug
<img width="844" alt="image" src="https://github.com/user-attachments/assets/de3c1acd-199a-40e2-9508-200f5ab5ab6c">

argument of type 'int' not iterable

### Steps to reproduce

this wont work and will produce error
    {
        "type": "numeric",
        "question": "how many years of work experience do you have with python (programming language)?",
        **"answer": 6**
    },

but this will
    {
        "type": "numeric",
        "question": "how many years of work experience do you have with python (programming language)?",
        **"answer": "6"**
    },

### Expected behavior

if the answer in answer.json is in int format there shouldn't be issue parsing and filling it in the form

### Actual behavior

(failing to parse answer.json when answer is in 'int' format) 

### Branch

None

### LLM Used

ChatGPT

### Model used

GPT4-0-mini

**Comment by akashbilgi** [comment]
2024-10-24 11:46:04.564 | ERROR    | src.aihawk_easy_applier:fill_up:346 - Failed to find form elements: argument of type 'int' is not iterable

**Comment by akashbilgi** [comment]
Can i fix this @feder-cr

**Comment by feder-cr** [comment]
@akashbilgi i will accept your PR

**Comment by feder-cr** [comment]
@akashbilgi @MuilaerteJunior join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
