### ISSUE TITLE
[FEATURE]: Add "Back to Top" Button for Enhanced Navigation

### ISSUE THREAD

**Issue by SagarSharma101** [feder-cr/Auto_Jobs_Applier_AIHawk#600]
### Feature summary

A "Back to Top" button that allows users to quickly return to the top of the page without manual scrolling.

### Feature description

This feature involves adding a "Back to Top" button that is always visible in a fixed position on the screen, such as the bottom right corner. When clicked, it smoothly scrolls the user back to the top of the page. The button should be styled in line with the existing UI to ensure a seamless look and feel.

### Motivation

This feature would be beneficial to improve user navigation, especially on longer pages with a lot of content. It saves users the time and effort of manually scrolling and enhances usability by making top-level navigation easier to access.

### Alternatives considered

I considered suggesting a keyboard shortcut reminder for scrolling to the top, but this wouldn’t be as intuitive or accessible for all users. Another option could be a floating sidebar, but that may clutter the page visually.

### Additional context

Adding this button would align with best practices in user experience by providing an easy way to navigate, especially for users who may not be aware of shortcuts.

**Comment by SagarSharma101** [comment]
assign me if needed

**Comment by feder-cr** [comment]
@SagarSharma101 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by SagarSharma101** [comment]
i thought we need to wait for response before sending pr...oh well
