### ISSUE TITLE
[BUG]: every answer is being written to answers.json

### ISSUE THREAD

**Issue by sarob** [feder-cr/Auto_Jobs_Applier_AIHawk#605]
### Describe the bug

it should be skipping write if answer is found and used

### Steps to reproduce

run `python main.py`

### Expected behavior

it should be skipping write if answer is found and used

### Actual behavior

very answer is being written to answers.json

### Branch

main

### Python version

3.10.14

### LLM Used

gemini

### Model used

gemini-pro

**Comment by FrancescoVassalli** [comment]
I believe this is the same issue 

https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/612
