### ISSUE TITLE
[BUG]: Keeps looping on same page on LinkedIn with page 0, page 1, page 2,....

### ISSUE THREAD

**Issue by rkhandelwal** [feder-cr/Auto_Jobs_Applier_AIHawk#620]
### Describe the bug

Not searching and navigating to the next title in the list. Seems stuck in a loop on the first title, duplicated entries in data.json

### Expected behavior

Should move to the next title in the search list

### Actual behavior

Keeps looping on the first title even though there are no matching jobs found

### Branch

main

### Python version

3.11.5

**Comment by hwasiti** [comment]
I have the same issue. Why the issue closed? Is the bug solved in a later commit?
