### ISSUE TITLE
[BUG]:how many years is hard coded to 0

### ISSUE THREAD

**Issue by akashbilgi** [feder-cr/Auto_Jobs_Applier_AIHawk#622]
### Describe the bug

when question with how many years is aked the answer is alwys hard coded to 0

### Steps to reproduce

![image](https://github.com/user-attachments/assets/e869d627-3698-4c5e-a661-13ceb1f3e210)

### Branch

None

**Comment by akashbilgi** [comment]
<img width="569" alt="2024-10-26_20h32_32" src="https://github.com/user-attachments/assets/b500f84c-bd3b-4ebb-83d3-4dad52e3cf27">

**Comment by surapuramakhil** [comment]
@sloganking can you review this MR.
