### ISSUE TITLE
[HELP WANTED]: Fix Error Handling for Missing failed.json File in Job Application Process

### ISSUE THREAD

**Issue by flyapex** [feder-cr/Auto_Jobs_Applier_AIHawk#630]
### Issue description

pull request addresses the issue encountered during the job application process, specifically the error logged as follows:

`ERROR    | src.aihawk_job_manager:start_applying:158 - Error during job application: [Errno 2] No such file or directory: 'data_folder/output/failed.json'`

It is not currently applying for jobs
![image](https://github.com/user-attachments/assets/fcd314b6-607b-4531-b1ae-6be0a56f9a57)

**Comment by Alkhalid3** [comment]
Issue is not fixed

**Comment by slat83** [comment]
issue is fixed in https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/641/files but not in the main release. When inserting code path directly is applied
