### ISSUE TITLE
[HELP WANTED]: Apply for multiple positions at a company?

### ISSUE THREAD

**Issue by shiboby** [feder-cr/Auto_Jobs_Applier_AIHawk#635]
### Issue description

My question is in regards to the field "apply_once_at_company". If I select true, does this mean it will only apply once at a company for only one position? I'd want to apply multiple times to a company if there are multiple appropriate positions or the position is with the same company but at different locations. Furthermore, does this apply only to each instance the script is once, or will it never apply to the same company again if it already applied to the company?

### Specific tasks

apply_once_at_company

**Comment by FrancescoVassalli** [comment]
If you want to apply to multiple positions you need to turn this flag to false

**Comment by shiboby** [comment]
Will this then apply to the same job multiple times? Or is there something that will limit the bot to only applying to each position once?

**Comment by FrancescoVassalli** [comment]
> Will this then apply to the same job multiple times? Or is there something that will limit the bot to only applying to each position once?

It will not apply to the same job multiple times because linkedin itself already prevents that

**Comment by shiboby** [comment]
What about if it is the same position at the same company, but a different location?

**Comment by FrancescoVassalli** [comment]
Then it probably will apply depending on your geographic filters

**Comment by shiboby** [comment]
Cool. Thank you for your answers!
