### ISSUE TITLE
[GOOD FIRST ISSUE]: Reduce sleeping time

### ISSUE THREAD

**Issue by shiboby** [feder-cr/Auto_Jobs_Applier_AIHawk#638]
### Issue summary

Reduce or remove the 60 seconds of sleep between searches for job titles

### Detailed description

How can I remove the the 60 seconds of sleep that the bot takes between different searches for different job titles? I know I can just type "y" and hit enter, but then I can't just leave the bot run. Any help would be greatly appreciated.

**Comment by GuilhermeRameh** [comment]
hello, can this be assinged to me? i would like to work on this

**Comment by FrancescoVassalli** [comment]
app_config.py has a const MINIMUM_WAIT_TIME I think you can just lower this

**Comment by cjbbb** [comment]
@surapuramakhil Can we add this to readme.md, Since I saw a lot of discussions about it.

**Comment by shiboby** [comment]
I made the changes in app_config.py to 10 seconds but it still says "Timeout 60 seconds" when running in the terminal.

**Comment by GuilhermeRameh** [comment]
@surapuramakhil i tried using the link in the README, but i think its expired, do you have another link i could try?

**Comment by surapuramakhil** [comment]
try this link: https://discord.gg/mMZcMTH9K6

**Comment by GuilhermeRameh** [comment]
Should i implement something different for this issue?

**Comment by GuilhermeRameh** [comment]
As sugested, i changed the MINIMUM_WAI_TIME directly on this PR. If theres anything else to do, im happy to help!
