### ISSUE TITLE
[BUG]: ERROR    | __main__:main:220 - Runtime error: Error running the bot: 'exam'

### ISSUE THREAD

**Issue by rrshan37** [feder-cr/Auto_Jobs_Applier_AIHawk#646]
could any one help resolve this issue

education_details:
  - education_level: "Master's Degree"
    institution: "GIET"
    field_of_study: "Engineering"
    final_evaluation_grade: "4.0"
    year_of_completion: "2018"
    start_date: "2016"
    additional_info:
      exam:
        Civil: "A"
        Structural: "A"

**Comment by SantoshAdabala** [comment]
I just created a clone in my machine and I changed it in my local machine. Could you please assign it to me.

**Comment by rrshan37** [comment]
> I just created a clone in my machine and I changed it in my local machine. Could you please assign it to me.

unable to assign
