### ISSUE TITLE
[BUG]: 2024-10-28 23:40:43.000 | ERROR    | __main__:main:219 - Runtime error: Error running the bot: 'exam'

### ISSUE THREAD

**Issue by zhiyang0218** [feder-cr/Auto_Jobs_Applier_AIHawk#654]
### Steps to reproduce

I am 100% sure the yaml file is correct.  Tried Python 3.11.9 and 3.13, but all not working. Saw similar problems, but not helpful. 
<img width="851" alt="6355a2b24f9547f645a2d3afbab2dbc" src="https://github.com/user-attachments/assets/981436b2-f921-499e-9351-9bb1be146e8c">

### Branch

main

### Python version

3.12.5(64bit)

### Model used

GPT-4o

**Comment by zhiyang0218** [comment]
Thanks for help!

**Comment by surapuramakhil** [comment]
@zhiyang0218 can you add full stack trace of your error.

**Comment by zhiyang0218** [comment]
@surapuramakhil I m not sure how to get a full stack trace in command prompt... Is this enough?
<img width="719" alt="f0ceb7735146966d5c707e298b02dfc" src="https://github.com/user-attachments/assets/7452f1c2-b1e1-4501-b453-c4f6399a95f5">

**Comment by ravigithubshankar** [comment]
It's getting same problem for us

**Comment by surapuramakhil** [comment]
@zhiyang0218 can you share why are you running with -m pdb? where did you find this instructions?

can you follow https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk?tab=readme-ov-file#installation Step 4 & 5

After you activate you venv. Run the bot - https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk?tab=readme-ov-file#installation

```sh
python main.py
```

**Comment by zhiyang0218** [comment]
@surapuramakhil I followed your instructions, and the bot can now search for jobs. However, it does not record any available positions or apply for them. Here are the error messages. By the way, I realized there is nothing in the output folder. 
<img width="875" alt="885c1ac07d7eb47cddc405f190fe4e5" src="https://github.com/user-attachments/assets/0fe526d3-450b-4034-8756-b41ba27fb86b">
<img width="1015" alt="18a292af615c6cb773906e0e444efc1" src="https://github.com/user-attachments/assets/61a5b119-f660-4d55-9c97-b800c2f28814">
<img width="836" alt="9f87f5271d9d2e0fb6f44943ba57ce9" src="https://github.com/user-attachments/assets/4b6e9835-e8d3-43ab-a548-40bde3e80210">

**Comment by zhiyang0218** [comment]
I saw the instructions in the troubleshooting part:

5. Bot Logs In But Doesn't Apply to Jobs
Issue: Bot searches for jobs but continues scrolling without applying

Solution:
Check for security checks or CAPTCHAs
Verify config.yaml job search parameters
Ensure your account profile meets job requirements
Review console output for error messages

I believe my yaml file and profile work, but I m not sure how to Check for security checks or CAPTCHAs and debug through the error message. QAQ

**Comment by AlexCerullo** [comment]
I had this error and fixed it. Make sure you do not change any formatting in your plain_text_resume.yaml file. Do not remove any sections, if needed, just leave them empty.

**Comment by zhiyang0218** [comment]
> I had this error and fixed it. Make sure you do not change any formatting in your plain_text_resume.yaml file. Do not remove any sections, if needed, just leave them empty.

What if I want to add more sections? like one more education level? Wil that cause any problems?
