### ISSUE TITLE
[BUG]: bot keeps applying for non relevant jobs!

### ISSUE THREAD

**Issue by avenarius-argus** [feder-cr/Auto_Jobs_Applier_AIHawk#660]
### Describe the bug

bot keeps applying for non relevant jobs, but never applied for relevant ones.

### Steps to reproduce

a fraction in my config.yaml:
positions:
  - Software engineer
  - Software Intern
  - Web Developer
  - Backend
  - Full Stack Developer
  - Devops
  - Cloud Engineer
  - Site Reliability Engineer
  - Business Intelligence
  - Software
  - AI

locations:
  - United States
  - California
  - Austin
  - Seattle
  - Boston
  - San Jose
  - Chicago
  - Portland
  - Washington DC
  - New York
  - San Francisco

apply_once_at_company: true

distance: 100

company_blacklist:

title_blacklist:
  - Sales
  - Marketing
  - Customer Service
  - HR
  - Trainer
  - Senior
  - Data
  - Consultant
  - Customer
  - Manager

location_blacklist:
  - Brazil
  - India
  - Mexico
  
 The job that bot applied:
![image](https://github.com/user-attachments/assets/faa7e0b6-6943-4069-ae3b-33edbea4b8f2)
I believe the bot keeps applying for jobs that does not have the key word I provided, nor does the blacklist works, as it's still applying for data, or hr related jobs.
Thank you.

### Branch

main

### Branch name

main

### Python version

3.11.3

### LLM Used

chatgpt

### Model used

gpt-4o-mini

**Comment by AbhishekShukla1289** [comment]
Any response from anyone?

**Comment by 49Simon** [comment]
Use the branch `release/v11.01.2024` it has a feature where it check the job suitability before applying. It sends the candidate profile and job description to LLM and gets a job suitability score. It only applies to jobs with `score >= 7`

**Comment by cjbbb** [comment]
we will merge release/v11.01.2024 with main today. Pls have a try!
