### ISSUE TITLE
[GOOD FIRST ISSUE]: Encapsulate sleep timers

### ISSUE THREAD

**Issue by FrancescoVassalli** [feder-cr/Auto_Jobs_Applier_AIHawk#661]
### Issue summary

Encapsulate sleep timers

### Detailed description

slightly better code would be to not have so many literals floating around. I propose to encapsulate the sleep timers in a medium or short sleep function in the utils. This will make editing these in the future more simple

### Expected outcome

encapsulated sleep timers

**Comment by FrancescoVassalli** [comment]
please assign to me

**Comment by cjbbb** [comment]
we do need to refactor parts of coding, thx for your help!
