### ISSUE TITLE
[FEATURE]: Option to skip applications where a years of experience answer is 0

### ISSUE THREAD

**Issue by FrancescoVassalli** [feder-cr/Auto_Jobs_Applier_AIHawk#669]
### Feature summary

Skip applications with lack of experience

### Feature description

I propose that we make an option for:
if the previously given answer for a question that contains the phrase "years of experience" is 0 then the application is skipped.  

Usecase Senario:
For my use case I am not a new grad so I have for examples questions like "How many years of python development experience do you have? Answer: 6" And other questions like "How many years of angular development experience do you have? Answer: 0". Well I do not want to apply to jobs that ask about angular because I do not know angular nor do I want to learn. So basically anytime a job asks about a skill and I have 0 years of experience with that technology I want to skip the job.

### Motivation

Less wasteful applications

### Alternatives considered

I honestly cannot think of one but I am happy to hear them

**Comment by surapuramakhil** [comment]
@FrancescoVassalli what you are trying to do here?

**Comment by FrancescoVassalli** [comment]
> @FrancescoVassalli what you are trying to do here?

Make the bot skip the application if the answer to one of the "years of experience" questions is 0. I am thinking this would be an option.

**Comment by surapuramakhil** [comment]
@FrancescoVassalli do you mean skipping application especially if it has question like "years of experience" and when you are a fresh grad - without any experience

**Comment by FrancescoVassalli** [comment]
> @FrancescoVassalli do you mean skipping application especially if it has question like "years of experience" and when you are a fresh grad - without any experience

For my use case I am not a new grad so I have for examples questions like "How many years of python development experience do you have? Answer: 6" And other questions like "How many years of angular development experience do you have? Answer: 0". Well I do not want to apply to jobs that ask about angular because I do not know angular nor do I want to learn. So basically anytime a job asks about a skill and I have 0 years of experience with that technology I want to skip the job.

**Comment by surapuramakhil** [comment]
Okay Gotchu. it's a feature.

so, you want to add skills blacklist and enhance blacklist for having additional check - detecting blacklist while answering questions.

Did I get it correct?

**Comment by FrancescoVassalli** [comment]
Instead of adding a blacklist, I was thinking to use the answers from
answers.json. The problem with the blacklist is that I would have to
blacklist every skill that I do not know. However, one does not know what
they do not know. If answers.json was used then the AI completions +
answers the user has adjusted in answers.json could provide the indicator
for if the job should be skipped.

**Comment by surapuramakhil** [comment]
I guess in release branch job suitability feature exists, maybe you can use that by setting it 10. Applying only to the jobs if your profile matches 100% to Job Description.

**Comment by surapuramakhil** [comment]
@FrancescoVassalli this MR solves it https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/555 not a strict check but AI check - where you can configure level

**Comment by FrancescoVassalli** [comment]
> @FrancescoVassalli this MR solves it #555 not a strict check but AI check - where you can configure level

I think this is a reasonable alternative for now. Let's hold off on my idea and see how this performs ?
