### ISSUE TITLE
[BUG]: resumes passed using `--resume` not used, wrongly attempts to call LLM API to generate resume

### ISSUE THREAD

**Issue by alxmke** [feder-cr/Auto_Jobs_Applier_AIHawk#684]
### Describe the bug

the program wrongly prompts for style, and seemingly fails to use the provided resume document at all, and instead tries to generate documents using your LLM API key (at least it does for me, on Windows). another thing: i'm not sure if this is expected behavior, but it scrolls to the bottom of the job results page and back up, and then clicks on one job and then scrolls all the way to the bottom of that job's page and back up too.  running `python main.py --resume data_folder\resume.pdf` gives:  ``` 2024-10-30 14:25:58.118 | ERROR    | src.llm.llm_manager:__call__:293 - Unexpected error occurred: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}} ```

### Steps to reproduce

1. use current main brainch
2. run `python main.py --resume data_folder\resume.pdf`
3. wait for first job to be clicked on
4. see error:

```
2024-10-30 14:25:58.118 | ERROR    | src.llm.llm_manager:__call__:293 - Unexpected error occurred: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
```

### Expected behavior

there should be no error, and the user-provided pdf should be used

### Actual behavior

the program attempts to use the user's LLM API key to generate documents, and the user-provided pdf is unused

### Branch

main

### Python version

3.11.4

### LLM Used

should not apply (but chat gpt)

### Model used

should not apply

**Comment by FrancescoVassalli** [comment]
I believe it still calls the OPEN AI API when you provide a resume in order to answer the questions job applications have. This does not mean a resume is being generated. Did you pay OPEN AI $5  and wait 12 hours for them to increase your rate limit ?
