### ISSUE TITLE
[BUG]: Fails to apply to jobs even after meeting suitability score

### ISSUE THREAD

**Issue by hiashley** [feder-cr/Auto_Jobs_Applier_AIHawk#686]
### Describe the bug

It doesn't apply to any jobs even if I meet the minimum job suitable score. I even put the minimum score as 1 and it still says I don't meet it. 

### Steps to reproduce

![Screen_Shot_2024-10-30_at_12 16 40_PM (1)](https://github.com/user-attachments/assets/4797c1b9-c437-4788-b81e-324b8a0b413b)
![Screen_Shot_2024-10-30_at_12 17 01_PM (1)](https://github.com/user-attachments/assets/c85d25e0-f131-443c-84f5-56c312eb63b3)

### Expected behavior

It should start applying if I meet the minimum suitability score.

### Actual behavior

It fails to apply.

### Branch

other

### Branch name

release-v11-01-2024

### Python version

3.12.5

### LLM Used

Gemini

### Model used

gemini-1.5-flash

**Comment by 49Simon** [comment]
I will work on this.

**Comment by FrancescoVassalli** [comment]
I think this should be closed
