### ISSUE TITLE
[QUESTION]: Tool tested, but..

### ISSUE THREAD

**Issue by mcnugets** [feder-cr/Auto_Jobs_Applier_AIHawk#702]
### Summary of your question

I've tested the tool couple of times, but i was wondering how can I get the confirmaton in a form of  response

### Question details

I populated my data.json where it shows the applied jobs via tool where I can trace all the vacancies, however I would like to know if we get confirmation in a form of email confirmation or any different source to reassure the job was indeed applied. Also I it possible to monitor what kind of resume  is being generated my llm

**Comment by v1gneshn** [comment]
what is the solution for this?
